import { parseJsonRequest } from "../../../../../lib/auth/input";
import { confirmMarketplaceServiceCheckout } from "../../../../../lib/billing/marketplace-service";
import { BillingDomainError } from "../../../../../lib/billing/checkout-service";
import { paymentFoundationStatus } from "../../../../../lib/billing/foundation";
import { billingErrorMessage } from "../../../../../lib/billing/localization";
import { assertSafeWrite, requireApiUser, withApiErrors } from "../../../../../lib/document-builder/auth/api";
import { requireD1, runtimeEnv } from "../../../../../lib/document-builder/storage/runtime";
import { workspaceForUser, workspaceForUserById } from "../../../../../lib/platform/workspace";
import { z } from "zod";
const body=z.object({requestId:z.uuid(),locale:z.enum(["ru","uz","en"]),accountType:z.enum(["individual","entrepreneur","lawyer","business"]),workspaceId:z.string().optional()}).strict(); type Ctx={params:Promise<{orderId:string}>};
export const POST=withApiErrors(async(r:Request,c:Ctx)=>{assertSafeWrite(r);const u=await requireApiUser(),p=await parseJsonRequest(r,body,1024),{orderId}=await c.params;if(!p.ok)return Response.json({code:"INVALID_INPUT"},{status:400});const state=paymentFoundationStatus(runtimeEnv());if(!state.enabled||!state.sandboxEnabled)return Response.json({code:"PAYMENT_METHOD_UNAVAILABLE"},{status:503});const w=p.data.workspaceId?await workspaceForUserById(u.id,p.data.workspaceId):await workspaceForUser(u);if(!w)return Response.json({code:"ORDER_UNAVAILABLE"},{status:404});const base=p.data.accountType==="business"&&p.data.workspaceId?`/${p.data.locale}/business/${encodeURIComponent(p.data.workspaceId)}`:`/${p.data.locale}/${p.data.accountType}`;try{return Response.json(await confirmMarketplaceServiceCheckout(requireD1(),{userId:u.id,workspaceId:w.id},orderId,p.data.requestId,`${base}/orders/${encodeURIComponent(orderId)}/payment`));}catch(e){if(e instanceof BillingDomainError)return Response.json({code:e.code,error:billingErrorMessage(e.code,p.data.locale)},{status:e.status});throw e;}});
