import { sha256 } from "../auth/crypto";
import { buildCapturedPaymentLedger } from "./ledger";
import type { sandboxPaymentEventSchema } from "./input";
import type { z } from "zod";

type Event = z.infer<typeof sandboxPaymentEventSchema>;
type Row = { attemptId:string; amountMinor:number; orderId:string; workspaceId:string; customerUserId:string; proposalId:string; lawyerProfileId:string; lawyerUserId:string; lawyerBaseAmountMinor:number; lawyerVatAmountMinor:number; lawyerGrossAmountMinor:number; juroBaseAmountMinor:number; juroVatAmountMinor:number; juroGrossAmountMinor:number; clientTotalMinor:number; expectedProviderSettlementMinor:number; lawyerExpectedPayoutMinor:number; juroExpectedRevenueMinor:number; taxPolicyVersionId:string; pricingPolicyVersionId:string; };

export async function finalizeMarketplaceServiceSandboxPayment(db:D1Database,event:Event,rawBody:string,now=new Date()) {
  const row=await db.prepare(`SELECT a.id AS attemptId,a.amount_minor AS amountMinor,o.id AS orderId,o.workspace_id AS workspaceId,o.customer_user_id AS customerUserId,p.id AS proposalId,p.lawyer_profile_id AS lawyerProfileId,p.lawyer_user_id AS lawyerUserId,s.lawyer_base_amount_minor AS lawyerBaseAmountMinor,s.lawyer_vat_amount_minor AS lawyerVatAmountMinor,s.lawyer_gross_amount_minor AS lawyerGrossAmountMinor,s.juro_base_amount_minor AS juroBaseAmountMinor,s.juro_vat_amount_minor AS juroVatAmountMinor,s.juro_gross_amount_minor AS juroGrossAmountMinor,s.client_total_minor AS clientTotalMinor,s.expected_provider_settlement_minor AS expectedProviderSettlementMinor,s.lawyer_expected_payout_minor AS lawyerExpectedPayoutMinor,s.juro_expected_revenue_minor AS juroExpectedRevenueMinor,s.tax_policy_version_id AS taxPolicyVersionId,s.pricing_policy_version_id AS pricingPolicyVersionId FROM payment_attempts a JOIN marketplace_orders o ON o.id=a.order_id JOIN order_agreements ag ON ag.order_id=o.id JOIN legal_service_proposals p ON p.id=ag.proposal_id JOIN pricing_snapshots s ON s.id=o.accepted_pricing_snapshot_id WHERE a.provider='sandbox' AND a.provider_attempt_id=? AND a.internal_status='client_action_required' AND o.status='AWAITING_PAYMENT' AND o.order_type='LEGAL_SERVICE' LIMIT 1`).bind(event.providerAttemptId).first<Row>();
  if(!row) throw new Error("PAYMENT_ATTEMPT_UNAVAILABLE");
  if(event.amountMinor!==row.amountMinor || event.amountMinor!==row.clientTotalMinor || event.currency!=="UZS") throw new Error("PAYMENT_AMOUNT_MISMATCH");
  const at=now.toISOString(), payloadSha256=await sha256(rawBody);
  if(event.type==='payment.failed') { await db.batch([
    db.prepare("INSERT INTO payment_provider_events (id,provider,provider_event_id,event_type,payload_sha256,signature_verified,internal_status,order_id,payment_attempt_id,received_at,processed_at) VALUES (?,'sandbox',?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),event.eventId,event.type,payloadSha256,1,"processed",row.orderId,row.attemptId,at,at),
    db.prepare("UPDATE payment_attempts SET internal_status='failed',provider_status='declined',failed_at=?,updated_at=? WHERE id=?").bind(at,at,row.attemptId),
    db.prepare("UPDATE marketplace_orders SET provider_status='declined',failed_at=?,updated_at=? WHERE id=?").bind(at,at,row.orderId),
  ]); return { replay:false, orderId:row.orderId,orderStatus:"AWAITING_PAYMENT",paymentId:null }; }
  const pricing={currency:"UZS" as const,lawyerBaseAmountMinor:row.lawyerBaseAmountMinor,lawyerVatAmountMinor:row.lawyerVatAmountMinor,lawyerGrossAmountMinor:row.lawyerGrossAmountMinor,juroBaseAmountMinor:row.juroBaseAmountMinor,juroVatAmountMinor:row.juroVatAmountMinor,juroGrossAmountMinor:row.juroGrossAmountMinor,subscriptionCreditMinor:0,discountAmountMinor:0,providerCommissionRateBasisPoints:0,providerCommissionBaseMinor:row.clientTotalMinor,providerCommissionAmountMinor:0,lawyerCommissionShareMinor:0,juroCommissionShareMinor:0,clientTotalMinor:row.clientTotalMinor,expectedProviderSettlementMinor:row.expectedProviderSettlementMinor,lawyerExpectedPayoutMinor:row.lawyerExpectedPayoutMinor,juroExpectedRevenueMinor:row.juroExpectedRevenueMinor,taxPolicyVersionId:row.taxPolicyVersionId,pricingPolicyVersionId:row.pricingPolicyVersionId,calculatedAt:at};
  const posting=buildCapturedPaymentLedger(pricing,"JURO_REVENUE"), paymentId=crypto.randomUUID(), tx=`ledger:${event.eventId}`, allocationId=crypto.randomUUID(); const accounts=[...new Set(posting.entries.map(e=>e.accountCode))];
  await db.batch([
    db.prepare("INSERT INTO payment_provider_events (id,provider,provider_event_id,event_type,payload_sha256,signature_verified,internal_status,order_id,payment_attempt_id,received_at,processed_at) VALUES (?,'sandbox',?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),event.eventId,event.type,payloadSha256,1,"processed",row.orderId,row.attemptId,at,at),
    db.prepare("INSERT INTO payments (id,workspace_id,subscription_id,provider_payment_id,amount_minor,currency,status,created_at,updated_at) VALUES (?,?,NULL,? ,?,'UZS','settled',?,?)").bind(paymentId,row.workspaceId,event.eventId,event.amountMinor,at,at),
    db.prepare("UPDATE payment_attempts SET payment_id=?,internal_status='settled',provider_status='funded',settled_at=?,updated_at=? WHERE id=?").bind(paymentId,at,at,row.attemptId),
    db.prepare("UPDATE marketplace_orders SET status='ACTIVE',provider_status='funded',settled_at=?,updated_at=? WHERE id=?").bind(at,at,row.orderId),
    db.prepare("UPDATE legal_service_proposals SET status='FUNDED',updated_at=? WHERE id=? AND status='ACCEPTED'").bind(at,row.proposalId),
    ...accounts.map(code=>db.prepare("INSERT OR IGNORE INTO ledger_accounts (id,owner_type,owner_id,code,currency,status,created_at) VALUES (?,?,? ,?,'UZS','active',?)").bind(`ledger:platform:JURO:${code}:UZS`,code==="LAWYER_PAYABLE"?"lawyer":"platform",code==="LAWYER_PAYABLE"?row.lawyerProfileId:"JURO",code,at)),
    db.prepare("INSERT INTO ledger_transactions (id,external_id,workspace_id,order_id,payment_id,transaction_type,status,idempotency_key,currency,debit_total_minor,credit_total_minor,occurred_at,version,created_at,updated_at) VALUES (?,?,?,?,?,'payment_capture','draft',?,'UZS',0,0,?,1,?,?)").bind(tx,`ledger_ext_${event.eventId}`,row.workspaceId,row.orderId,paymentId,`sandbox:webhook:${event.eventId}`,event.occurredAt,at,at),
    ...posting.entries.map((e,i)=>db.prepare("INSERT INTO ledger_entries (id,transaction_id,account_id,sequence,side,amount_minor,currency,memo,created_at) VALUES (?,?,?,?,?,?,'UZS',?,?)").bind(`${tx}:${i+1}`,tx,`ledger:platform:JURO:${e.accountCode}:UZS`,i+1,e.side,e.amountMinor,e.memo,at)),
    db.prepare("UPDATE ledger_transactions SET status='posted',debit_total_minor=?,credit_total_minor=?,posted_at=?,updated_at=? WHERE id=?").bind(posting.debitMinor,posting.creditMinor,at,at,tx),
    db.prepare("INSERT INTO settlement_allocations (id,external_id,order_id,proposal_id,workspace_id,lawyer_profile_id,lawyer_user_id,allocation_type,status,gross_amount_minor,provider_fee_share_minor,net_amount_minor,currency,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'LEGAL_SERVICE','PENDING_SETTLEMENT',?,0,?,'UZS',?,?,?)").bind(allocationId,`alloc_${event.eventId}`,row.orderId,row.proposalId,row.workspaceId,row.lawyerProfileId,row.lawyerUserId,row.lawyerGrossAmountMinor,row.lawyerExpectedPayoutMinor,`capture:${event.eventId}`,at,at),
    db.prepare("INSERT INTO lawyer_payables (id,external_id,settlement_allocation_id,order_id,workspace_id,lawyer_profile_id,lawyer_user_id,status,amount_minor,currency,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'PENDING_SETTLEMENT',?,'UZS',?,?,?)").bind(crypto.randomUUID(),`payable_${event.eventId}`,allocationId,row.orderId,row.workspaceId,row.lawyerProfileId,row.lawyerUserId,row.lawyerExpectedPayoutMinor,`capture:${event.eventId}`,at,at),
    db.prepare("INSERT INTO workspace_audit_events (id,workspace_id,actor_user_id,entity_type,entity_id,action,metadata_json,created_at) VALUES (?,?,?,'marketplace_order',?,'legal_service_payment_funded',?,?)").bind(crypto.randomUUID(),row.workspaceId,row.customerUserId,row.orderId,JSON.stringify({eventId:event.eventId,paymentId,allocationId}),at),
  ]); return { replay:false,orderId:row.orderId,orderStatus:"ACTIVE",paymentId };
}
