const UZ_TITLES: Readonly<Record<string, string>> = {
  "О вызове свидетелей в судебное заседание": "Guvohlarni sud majlisiga chaqirish to‘g‘risida iltimosnoma",
  "О допуске представителя к участию в деле": "Vakilni ishda ishtirok etishga qo‘yish to‘g‘risida iltimosnoma",
  "О наложении ареста на имущество": "Mol-mulkni xatlash to‘g‘risida iltimosnoma",
  "О назначении автотехнической экспертизы": "Avtotexnik ekspertiza tayinlash to‘g‘risida iltimosnoma",
  "О назначении дополнительной экспертизы": "Qo‘shimcha ekspertiza tayinlash to‘g‘risida iltimosnoma",
  "О назначении экспертизы": "Ekspertiza tayinlash to‘g‘risida iltimosnoma",
  "О назначении медицинской экспертизы": "Tibbiy ekspertiza tayinlash to‘g‘risida iltimosnoma",
  "О назначении почерковедческой экспертизы": "Xatshunoslik ekspertizasini tayinlash to‘g‘risida iltimosnoma",
  "О назначении повторной экспертизы": "Takroriy ekspertiza tayinlash to‘g‘risida iltimosnoma",
  "О назначении психиатрической экспертизы": "Psixiatriya ekspertizasini tayinlash to‘g‘risida iltimosnoma",
  "О назначении строительной экспертизы": "Qurilish ekspertizasini tayinlash to‘g‘risida iltimosnoma",
  "О передаче дела в другой суд": "Ishni boshqa sudga o‘tkazish to‘g‘risida iltimosnoma",
  "Ходатайство об отложении судебного заседания": "Sud majlisini keyinga qoldirish to‘g‘risida iltimosnoma",
  "Ходатайство об обеспечении переводчиком": "Tarjimon bilan ta’minlash to‘g‘risida iltimosnoma",
  "Заявление о прекращении производства по делу": "Ish yuritishni tugatish to‘g‘risida ariza",
  "Ходатайство об отсрочке уплаты государственной пошлины": "Davlat bojini to‘lashni kechiktirish to‘g‘risida iltimosnoma",
  "Ходатайство о приобщении доказательств к материалам дела": "Dalillarni ish materiallariga qo‘shish to‘g‘risida iltimosnoma",
  "Ходатайство о восстановлении процессуального срока": "Protsessual muddatni tiklash to‘g‘risida iltimosnoma",
  "Ходатайство о рассмотрении дела без участия стороны": "Ishni taraf ishtirokisiz ko‘rish to‘g‘risida iltimosnoma",
  "Заявление о принятии мер по обеспечению иска": "Da’voni ta’minlash choralarini ko‘rish to‘g‘risida ariza",
  "Заявление о приостановлении исполнительного производства": "Ijro ishini yuritishni to‘xtatib turish to‘g‘risida ariza",
  "Ходатайство о привлечении дополнительного ответчика": "Qo‘shimcha javobgarni jalb qilish to‘g‘risida iltimosnoma",
  "Ходатайство о привлечении специалиста": "Mutaxassisni jalb qilish to‘g‘risida iltimosnoma",
  "Ходатайство о продлении процессуального срока": "Protsessual muddatni uzaytirish to‘g‘risida iltimosnoma",
  "Ходатайство о ведении аудио-видеозаписи судебного заседания": "Sud majlisining audio-video yozuvini yuritish to‘g‘risida iltimosnoma",
  "Заявление о разъяснении решения суда": "Sud qarorini tushuntirish to‘g‘risida ariza",
  "Заявление о направлении судебного поручения": "Sud topshirig‘ini yuborish to‘g‘risida ariza",
  "Ходатайство о назначении технической экспертизы": "Texnik ekspertiza tayinlash to‘g‘risida iltimosnoma",
  "Ходатайство о привлечении третьего лица к участию в деле": "Uchinchi shaxsni ishda ishtirok etishga jalb qilish to‘g‘risida iltimosnoma",
  "Ходатайство о восстановлении срока на подачу апелляционной жалобы": "Apellyatsiya shikoyatini berish muddatini tiklash to‘g‘risida iltimosnoma",
  "Заявление об отзыве искового заявления": "Da’vo arizasini qaytarib olish to‘g‘risida ariza",
  "Ходатайство о возврате государственной пошлины": "Davlat bojini qaytarish to‘g‘risida iltimosnoma",
  "Ходатайство о выдаче исполнительного листа": "Ijro varaqasini berish to‘g‘risida iltimosnoma",
  "Ходатайство о вынесении дополнительного решения": "Qo‘shimcha hal qiluv qarorini chiqarish to‘g‘risida iltimosnoma",
  "Ходатайство о вызове эксперта": "Ekspertni chaqirish to‘g‘risida iltimosnoma",
  "Ходатайство о взыскании судебных расходов": "Sud xarajatlarini undirish to‘g‘risida iltimosnoma",
  "Ходатайство о рассмотрении дела в закрытом судебном заседании": "Ishni yopiq sud majlisida ko‘rish to‘g‘risida iltimosnoma",
  "Ходатайство о замене ответчика": "Javobgarni almashtirish to‘g‘risida iltimosnoma",
  "Ходатайство о заочном рассмотрении дела": "Ishni sirtdan ko‘rish to‘g‘risida iltimosnoma",
  "Ходатайство об истребовании доказательств": "Dalillarni talab qilib olish to‘g‘risida iltimosnoma",
  "Ходатайство об истребовании документов": "Hujjatlarni talab qilib olish to‘g‘risida iltimosnoma",
  "Ходатайство об изменении основания иска": "Da’vo asosini o‘zgartirish to‘g‘risida iltimosnoma",
  "Заявление об отзыве ходатайства": "Iltimosnomani qaytarib olish to‘g‘risida ariza",
  "Заявление об уменьшении исковых требований": "Da’vo talablarini kamaytirish to‘g‘risida ariza",
  "Заявление об увеличении исковых требований": "Da’vo talablarini ko‘paytirish to‘g‘risida ariza",
  "Заявление об уточнении исковых требований": "Da’vo talablariga aniqlik kiritish to‘g‘risida ariza",
  "Заявление об утверждении мирового соглашения": "Kelishuv bitimini tasdiqlash to‘g‘risida ariza",
  "Заявление об отводе судьи": "Sudyani rad etish to‘g‘risida ariza",
  "Заявление об отмене обеспечительных мер по иску": "Da’voni ta’minlash choralarini bekor qilish to‘g‘risida ariza",
  "Заявление о прекращении производства по делу в связи с отказом от иска": "Da’vodan voz kechilganligi sababli ish yuritishni tugatish to‘g‘risida ariza",
  "Ходатайство о снижении размера неустойки": "Neustoyka miqdorini kamaytirish to‘g‘risida iltimosnoma",
  "Ходатайство об объединении гражданских дел": "Fuqarolik ishlarini birlashtirish to‘g‘risida iltimosnoma",
  "Ходатайство об ознакомлении с материалами гражданского дела": "Fuqarolik ishi materiallari bilan tanishish to‘g‘risida iltimosnoma",
  "Возражение на ходатайство": "Iltimosnomaga e’tiroz",
  "Ходатайство о снижении размера государственной пошлины": "Davlat boji miqdorini kamaytirish to‘g‘risida iltimosnoma",
  "Ходатайство о приостановлении производства по делу": "Ish yuritishni to‘xtatib turish to‘g‘risida iltimosnoma",
  "Ходатайство об ускорении рассмотрения дела": "Ishni ko‘rishni tezlashtirish to‘g‘risida iltimosnoma",
  "Заявление о пересмотре заочного решения": "Sirtdan chiqarilgan hal qiluv qarorini qayta ko‘rib chiqish to‘g‘risida ariza",
  "Заявление о выдаче копии решения": "Hal qiluv qarori nusxasini berish to‘g‘risida ariza",
  "Ходатайство о признании доказательств подложными": "Dalillarni qalbaki deb topish to‘g‘risida iltimosnoma",
  "Заявление об изменении предмета иска": "Da’vo predmetini o‘zgartirish to‘g‘risida ariza",
  "Заявление об изменении обеспечительных мер по иску": "Da’voni ta’minlash choralarini o‘zgartirish to‘g‘risida ariza",
  "Заявление об исправлении описки": "Yozuv xatosini tuzatish to‘g‘risida ariza",
  "Заявление о признании иска ответчиком": "Javobgar tomonidan da’voni tan olish to‘g‘risida ariza",
  "Заявление о выдаче дубликата исполнительного листа": "Ijro varaqasi dublikatini berish to‘g‘risida ariza",
  "Заявление о признании иска третьим лицом": "Uchinchi shaxs tomonidan da’voni tan olish to‘g‘risida ariza",
  "Заявление об отводе прокурора": "Prokurorni rad etish to‘g‘risida ariza",
  "Заявление о выдаче дубликата судебного приказа": "Sud buyrug‘i dublikatini berish to‘g‘risida ariza",
  "Заявление об обратном исполнении решения суда": "Sud qarorining qaytarma ijrosi to‘g‘risida ariza",
  "Заявление о выдаче копии протокола судебного заседания": "Sud majlisi bayonnomasi nusxasini berish to‘g‘risida ariza",
  "Заявление о применении последствий пропуска срока обращения в суд": "Sudga murojaat qilish muddati o‘tkazib yuborilganligi oqibatlarini qo‘llash to‘g‘risida ariza",
  "Заявление об отсрочке исполнения решения суда": "Sud qarori ijrosini kechiktirish to‘g‘risida ariza",
  "Заявление о выдаче копий документов": "Hujjatlar nusxalarini berish to‘g‘risida ariza",
  "Заявление о пересмотре решения суда по новым обстоятельствам": "Sud qarorini yangi holatlar bo‘yicha qayta ko‘rib chiqish to‘g‘risida ariza",
  "Исковое заявление о взыскании алиментов (на содержание истца)": "Da’vogar ta’minoti uchun aliment undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление об освобождении от уплаты задолженности по алиментам": "Aliment qarzdorligini to‘lashdan ozod qilish to‘g‘risida da’vo arizasi",
  "Исковое заявление об уменьшении размера алиментов": "Aliment miqdorini kamaytirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании неустойки по алиментам": "Aliment bo‘yicha neustoyka undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о перерасчёте и взыскании алиментов": "Alimentni qayta hisoblash va undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании алиментов в твёрдой денежной сумме": "Alimentni qat’iy pul summasida undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление об изменении установленного размера алиментов и взыскании алиментов в твёрдой денежной сумме": "Belgilangan aliment miqdorini o‘zgartirish va alimentni qat’iy pul summasida undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании алиментов на ребёнка": "Bola uchun aliment undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании алиментов на содержание совершеннолетнего нетрудоспособного ребёнка": "Voyaga yetgan mehnatga layoqatsiz bola ta’minoti uchun aliment undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о разделе имущества, нажитого в период брака": "Nikoh davrida orttirilgan mol-mulkni bo‘lish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании алиментов на содержание родителя": "Ota-ona ta’minoti uchun aliment undirish to‘g‘risida da’vo arizasi",
  "Заявление об отмене судебного приказа о взыскании алиментов": "Aliment undirish haqidagi sud buyrug‘ini bekor qilish to‘g‘risida ariza",
  "Исковое заявление об осуществлении родительских прав при раздельном проживании": "Alohida yashashda ota-onalik huquqlarini amalga oshirish to‘g‘risida da’vo arizasi",
  "Исковое заявление об оспаривании отцовства": "Otalikka e’tiroz bildirish to‘g‘risida da’vo arizasi",
  "Исковое заявление об установлении отцовства и взыскании алиментов": "Otalikni belgilash va aliment undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление об определении места жительства ребёнка": "Bolaning yashash joyini belgilash to‘g‘risida da’vo arizasi",
  "Исковое заявление об устранении препятствий к общению с ребёнком": "Bola bilan muloqot qilishga to‘sqinliklarni bartaraf etish to‘g‘risida da’vo arizasi",
  "Исковое заявление об установлении порядка общения с ребёнком": "Bola bilan muloqot qilish tartibini belgilash to‘g‘risida da’vo arizasi",
  "Исковое заявление об отмене усыновления (удочерения)": "Farzandlikka olishni bekor qilish to‘g‘risida da’vo arizasi",
  "Исковое заявление о восстановлении материнских (отцовских) прав": "Onalik (otalik) huquqlarini tiklash to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании недействительными заключения брака и его расторжения": "Nikoh tuzilganligi va uning bekor qilinishini haqiqiy emas deb topish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании ущерба в связи с признанием брака недействительным": "Nikoh haqiqiy emas deb topilganligi munosabati bilan zararni undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о расторжении брака": "Nikohdan ajratish to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании фиктивного брака недействительным": "Soxta nikohni haqiqiy emas deb topish to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании брака недействительным (супруг состоял в другом браке)": "Turmush o‘rtog‘i boshqa nikohda bo‘lganligi sababli nikohni haqiqiy emas deb topish to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании недействительными свидетельства о праве на наследство и завещания": "Merosga bo‘lgan huquq guvohnomasi va vasiyatnomani haqiqiy emas deb topish to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании завещания недействительным": "Vasiyatnomani haqiqiy emas deb topish to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании наследника недостойным": "Merosxo‘rni noloyiq deb topish to‘g‘risida da’vo arizasi",
  "Исковое заявление о восстановлении срока для принятия наследства": "Merosni qabul qilish muddatini tiklash to‘g‘risida da’vo arizasi",
  "Исковое заявление о разделе наследственного имущества": "Meros mol-mulkini bo‘lish to‘g‘risida da’vo arizasi",
  "Исковое заявление о разделе наследственного имущества (вариант 2)": "Meros mol-mulkini bo‘lish to‘g‘risida da’vo arizasi (2-variant)",
  "Исковое заявление о включении имущества в состав наследства": "Mol-mulkni meros tarkibiga kiritish to‘g‘risida da’vo arizasi",
  "Исковое заявление о восстановлении на работе и взыскании морального вреда": "Ishga tiklash va ma’naviy zarar undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании заработной платы и компенсации за задержку выплат": "Ish haqi va to‘lovlarni kechiktirganlik uchun kompensatsiya undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании невыплаченных премий": "To‘lanmagan mukofotlarni undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о выдаче трудовой книжки и иных документов после увольнения": "Ishdan bo‘shatilgandan keyin mehnat daftarchasi va boshqa hujjatlarni berish to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании трудовых отношений и понуждении работодателя к заключению трудового договора": "Mehnat munosabatlarini tan olish va ish beruvchini mehnat shartnomasi tuzishga majbur qilish to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании увольнения незаконным": "Ishdan bo‘shatishni noqonuniy deb topish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании задолженности по арендной плате": "Ijara haqi bo‘yicha qarzdorlikni undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о расторжении договора аренды и взыскании задолженности": "Ijara shartnomasini bekor qilish va qarzdorlikni undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании задолженности по кредитному договору": "Kredit shartnomasi bo‘yicha qarzdorlikni undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании гражданина недееспособным": "Fuqaroni muomalaga layoqatsiz deb topish to‘g‘risida da’vo arizasi",
  "Исковое заявление о расторжении договора купли-продажи": "Oldi-sotdi shartnomasini bekor qilish to‘g‘risida da’vo arizasi",
  "Исковое заявление о расторжении договора": "Shartnomani bekor qilish to‘g‘risida da’vo arizasi",
  "Исковое заявление об истребовании имущества из чужого незаконного владения": "Mol-mulkni o‘zganing noqonuniy egaligidan talab qilib olish to‘g‘risida da’vo arizasi",
  "Исковое заявление об исключении имущества из описи (снятии ареста)": "Mol-mulkni ro‘yxatdan chiqarish (xatlovni bekor qilish) to‘g‘risida da’vo arizasi",
  "О признании права собственности на земельный участок": "Yer uchastkasiga mulk huquqini tan olish to‘g‘risida da’vo arizasi",
  "О государственной регистрации перехода права собственности": "Mulk huquqi o‘tishini davlat ro‘yxatidan o‘tkazish to‘g‘risida da’vo arizasi",
  "О признании права собственности на часть жилого дома": "Turar joyning bir qismiga mulk huquqini tan olish to‘g‘risida da’vo arizasi",
  "О признании права собственности на автомобиль": "Avtomobilga mulk huquqini tan olish to‘g‘risida da’vo arizasi",
  "О признании права собственности": "Mulk huquqini tan olish to‘g‘risida da’vo arizasi",
  "О признании права собственности на гараж": "Garajga mulk huquqini tan olish to‘g‘risida da’vo arizasi",
  "Об устранении препятствий в пользовании имуществом": "Mol-mulkdan foydalanishdagi to‘sqinliklarni bartaraf etish to‘g‘risida da’vo arizasi",
  "О замене некачественного товара": "Sifatsiz tovarni almashtirish to‘g‘risida da’vo arizasi",
  "О защите прав потребителей и взыскании морального вреда": "Iste’molchilar huquqlarini himoya qilish va ma’naviy zarar undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании морального вреда": "Ma’naviy zarar undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании в порядке регресса": "Regress tartibida undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании вреда, причинённого здоровью гражданина": "Fuqaroning sog‘lig‘iga yetkazilgan zararni undirish to‘g‘risida da’vo arizasi",
  "О взыскании ущерба, причинённого автомобилю": "Avtomobilga yetkazilgan zararni undirish to‘g‘risida da’vo arizasi",
  "О взыскании ущерба, причинённого пожаром": "Yong‘in oqibatida yetkazilgan zararni undirish to‘g‘risida da’vo arizasi",
  "О взыскании материального ущерба с работника": "Xodimdan moddiy zararni undirish to‘g‘risida da’vo arizasi",
  "О взыскании ущерба, причинённого имуществу": "Mol-mulkka yetkazilgan zararni undirish to‘g‘risida da’vo arizasi",
  "О взыскании ущерба, причинённого несовершеннолетним": "Voyaga yetmagan shaxs yetkazgan zararni undirish to‘g‘risida da’vo arizasi",
  "О взыскании ущерба, причинённого преступлением": "Jinoyat oqibatida yetkazilgan zararni undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о выселении временно проживающих": "Vaqtincha yashovchilarni ko‘chirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о вселении в жилое помещение в принудительном порядке": "Turar joyga majburiy kiritish to‘g‘risida da’vo arizasi",
  "Исковое заявление о принудительном выселении из жилого дома": "Turar joydan majburiy ko‘chirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании утратившим право пользования жилым помещением и снятии с регистрационного учёта": "Turar joydan foydalanish huquqini yo‘qotgan deb topish va ro‘yxatdan chiqarish to‘g‘risida da’vo arizasi",
  "Исковое заявление о выселении из общежития": "Yotoqxonadan ko‘chirish to‘g‘risida da’vo arizasi",
  "Исковое заявление о признании права собственности на самовольную постройку": "O‘zboshimchalik bilan qurilgan imoratga mulk huquqini tan olish to‘g‘risida da’vo arizasi",
  "Исковое заявление о сносе самовольной постройки": "O‘zboshimchalik bilan qurilgan imoratni buzish to‘g‘risida da’vo arizasi",
  "Исковое заявление о взыскании ущерба, причинённого заливом квартиры": "Kvartirani suv bosishi oqibatida yetkazilgan zararni undirish to‘g‘risida da’vo arizasi",
  "Исковое заявление об определении порядка пользования жилым помещением": "Turar joydan foydalanish tartibini belgilash to‘g‘risida da’vo arizasi",
  "Исковое заявление об определении порядка пользования домом": "Uydan foydalanish tartibini belgilash to‘g‘risida da’vo arizasi",
  "Апелляционная жалоба на решение суда": "Sudning hal qiluv qarori ustidan apellyatsiya shikoyati",
};

export function getUzTitle(titleRu: string, code: string): string {
  return UZ_TITLES[titleRu] ?? `Yuridik hujjat loyihasi № ${code}`;
}
