/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.legal-corpus.jsonc --include-runtime=false --env-interface=LegalCorpusDevelopmentEnv worker/legal-corpus-development-configuration.d.ts` (hash: fa0fa431a314cb24b42e2883783c9bc3)
interface __BaseEnv_LegalCorpusDevelopmentEnv {
	BUCKET: R2Bucket;
	BACKUP_BUCKET: R2Bucket;
	LEGAL_EVIDENCE_BUCKET: R2Bucket;
	DB: D1Database;
	LEGAL_DB: D1Database;
	LEGAL_AI_SEARCH_NAMESPACE: AiSearchNamespace;
	APP_ENV: "staging" | "production" | "development";
	LEGAL_CORPUS_ENABLED: "true" | "false";
	LEGAL_CORPUS_AUTO_INGEST_ENABLED: "true" | "false";
	LEGAL_CORPUS_LIVE_LEXUZ_ENABLED: "true" | "false";
	LEGAL_CORPUS_MULTILINGUAL_ENABLED: "true" | "false";
	LEGAL_CORPUS_OWNER_UPLOAD_AUTO_TRUST: "true" | "false";
	LEGAL_CORPUS_USER_UPLOAD_AUTO_TRUST: "true" | "false";
	LEGAL_CORPUS_HISTORICAL_ENABLED: "true" | "false";
	LEGAL_CORPUS_DENSE_ENABLED: "true" | "false";
	LEGAL_CORPUS_SHADOW_MODE: "true" | "false";
	LEGAL_EVIDENCE_BUCKET_NAME: "juro-legal-evidence-staging-green2-20260831" | "juro-legal-evidence-production" | "juro-legal-evidence-development";
	LEGAL_AI_SEARCH_NAMESPACE_NAME: "juro-legal-staging" | "juro-legal-production" | "juro-legal-development";
	LEGAL_AI_SEARCH_CONFIGURATION_ID: "ai-search-staging-v1" | "ai-search-production-v1" | "ai-search-development-v1";
	LEGAL_AI_GATEWAY_ID: "juro-ai-search-staging" | "juro-ai-search-production" | "juro-ai-search-development";
	LEGAL_AI_PROVIDER_PROJECT_ID: "juro-openai-staging" | "juro-openai-production" | "juro-openai-development";
	LEGAL_AI_SEARCH_EMBEDDING_MODEL: "openai/text-embedding-3-large";
	LEGAL_AI_SEARCH_DIMENSIONS: "1536";
	LEGAL_AI_SEARCH_KEYWORD_TOKENIZER: "porter";
	LEGAL_AI_SEARCH_METADATA_SCHEMA: "language:text,document_type:text,valid_from:datetime,valid_to:datetime";
	LEGAL_AI_SEARCH_SOURCE_PREFIX: "search-releases/";
	LEGAL_AI_SEARCH_MAX_RESULTS: "50";
	LEGAL_AI_SEARCH_MAX_INSTANCES_PER_QUERY: "10";
	LEGAL_AI_SEARCH_PAUSED: "true";
	LEGAL_AI_SEARCH_GATEWAY_PAYLOAD_LOGGING: "false";
	LEGAL_AI_SEARCH_GATEWAY_CACHE: "false";
	LEGAL_AI_SEARCH_SIMILARITY_CACHE: "false";
	QDRANT_URL?: "https://qdrant.internal";
	QDRANT_COLLECTION?: "juro_legal_staging_provision_v1";
	LEGAL_CORPUS_INDEX_VERSION?: "staging-20260830-provision-v1";
	EMBEDDING_MODEL?: "text-embedding-3-large";
	OPENAI_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	OPENAI_MODEL: string;
	JURO_SMOKE_BASE_URL: string;
	RESEND_API_KEY: string;
	EMAIL_FROM: string;
	QDRANT_SERVICE?: Fetcher /* juro-platform-staging */;
	LEGAL_CORPUS_EMBEDDING_SERVICE?: Fetcher /* juro-platform-staging */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./legal-corpus-worker");
	}
	interface StagingEnv {
		BUCKET: R2Bucket;
		BACKUP_BUCKET: R2Bucket;
		LEGAL_EVIDENCE_BUCKET: R2Bucket;
		DB: D1Database;
		LEGAL_DB: D1Database;
		LEGAL_AI_SEARCH_NAMESPACE: AiSearchNamespace;
		APP_ENV: "staging";
		LEGAL_CORPUS_ENABLED: "true";
		LEGAL_CORPUS_AUTO_INGEST_ENABLED: "true";
		LEGAL_CORPUS_LIVE_LEXUZ_ENABLED: "true";
		LEGAL_CORPUS_MULTILINGUAL_ENABLED: "true";
		LEGAL_CORPUS_OWNER_UPLOAD_AUTO_TRUST: "true";
		LEGAL_CORPUS_USER_UPLOAD_AUTO_TRUST: "true";
		LEGAL_CORPUS_HISTORICAL_ENABLED: "true";
		LEGAL_CORPUS_DENSE_ENABLED: "true";
		LEGAL_CORPUS_SHADOW_MODE: "true";
		LEGAL_EVIDENCE_BUCKET_NAME: "juro-legal-evidence-staging-green2-20260831";
		LEGAL_AI_SEARCH_NAMESPACE_NAME: "juro-legal-staging";
		LEGAL_AI_SEARCH_CONFIGURATION_ID: "ai-search-staging-v1";
		LEGAL_AI_GATEWAY_ID: "juro-ai-search-staging";
		LEGAL_AI_PROVIDER_PROJECT_ID: "juro-openai-staging";
		LEGAL_AI_SEARCH_EMBEDDING_MODEL: "openai/text-embedding-3-large";
		LEGAL_AI_SEARCH_DIMENSIONS: "1536";
		LEGAL_AI_SEARCH_KEYWORD_TOKENIZER: "porter";
		LEGAL_AI_SEARCH_METADATA_SCHEMA: "language:text,document_type:text,valid_from:datetime,valid_to:datetime";
		LEGAL_AI_SEARCH_SOURCE_PREFIX: "search-releases/";
		LEGAL_AI_SEARCH_MAX_RESULTS: "50";
		LEGAL_AI_SEARCH_MAX_INSTANCES_PER_QUERY: "10";
		LEGAL_AI_SEARCH_PAUSED: "true";
		LEGAL_AI_SEARCH_GATEWAY_PAYLOAD_LOGGING: "false";
		LEGAL_AI_SEARCH_GATEWAY_CACHE: "false";
		LEGAL_AI_SEARCH_SIMILARITY_CACHE: "false";
		QDRANT_URL: "https://qdrant.internal";
		QDRANT_COLLECTION: "juro_legal_staging_provision_v1";
		LEGAL_CORPUS_INDEX_VERSION: "staging-20260830-provision-v1";
		EMBEDDING_MODEL: "text-embedding-3-large";
		OPENAI_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		OPENAI_MODEL: string;
		JURO_SMOKE_BASE_URL: string;
		RESEND_API_KEY: string;
		EMAIL_FROM: string;
		QDRANT_SERVICE: Fetcher /* juro-platform-staging */;
		LEGAL_CORPUS_EMBEDDING_SERVICE: Fetcher /* juro-platform-staging */;
	}
	interface ProductionEnv {
		BUCKET: R2Bucket;
		BACKUP_BUCKET: R2Bucket;
		LEGAL_EVIDENCE_BUCKET: R2Bucket;
		DB: D1Database;
		LEGAL_DB: D1Database;
		LEGAL_AI_SEARCH_NAMESPACE: AiSearchNamespace;
		APP_ENV: "production";
		LEGAL_CORPUS_ENABLED: "false";
		LEGAL_CORPUS_AUTO_INGEST_ENABLED: "false";
		LEGAL_CORPUS_LIVE_LEXUZ_ENABLED: "false";
		LEGAL_CORPUS_MULTILINGUAL_ENABLED: "false";
		LEGAL_CORPUS_OWNER_UPLOAD_AUTO_TRUST: "false";
		LEGAL_CORPUS_USER_UPLOAD_AUTO_TRUST: "false";
		LEGAL_CORPUS_HISTORICAL_ENABLED: "false";
		LEGAL_CORPUS_DENSE_ENABLED: "false";
		LEGAL_CORPUS_SHADOW_MODE: "false";
		LEGAL_EVIDENCE_BUCKET_NAME: "juro-legal-evidence-production";
		LEGAL_AI_SEARCH_NAMESPACE_NAME: "juro-legal-production";
		LEGAL_AI_SEARCH_CONFIGURATION_ID: "ai-search-production-v1";
		LEGAL_AI_GATEWAY_ID: "juro-ai-search-production";
		LEGAL_AI_PROVIDER_PROJECT_ID: "juro-openai-production";
		LEGAL_AI_SEARCH_EMBEDDING_MODEL: "openai/text-embedding-3-large";
		LEGAL_AI_SEARCH_DIMENSIONS: "1536";
		LEGAL_AI_SEARCH_KEYWORD_TOKENIZER: "porter";
		LEGAL_AI_SEARCH_METADATA_SCHEMA: "language:text,document_type:text,valid_from:datetime,valid_to:datetime";
		LEGAL_AI_SEARCH_SOURCE_PREFIX: "search-releases/";
		LEGAL_AI_SEARCH_MAX_RESULTS: "50";
		LEGAL_AI_SEARCH_MAX_INSTANCES_PER_QUERY: "10";
		LEGAL_AI_SEARCH_PAUSED: "true";
		LEGAL_AI_SEARCH_GATEWAY_PAYLOAD_LOGGING: "false";
		LEGAL_AI_SEARCH_GATEWAY_CACHE: "false";
		LEGAL_AI_SEARCH_SIMILARITY_CACHE: "false";
		OPENAI_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		OPENAI_MODEL: string;
		JURO_SMOKE_BASE_URL: string;
		RESEND_API_KEY: string;
		EMAIL_FROM: string;
	}
	interface Env extends __BaseEnv_LegalCorpusDevelopmentEnv {}
}
interface LegalCorpusDevelopmentEnv extends __BaseEnv_LegalCorpusDevelopmentEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "LEGAL_CORPUS_ENABLED" | "LEGAL_CORPUS_AUTO_INGEST_ENABLED" | "LEGAL_CORPUS_LIVE_LEXUZ_ENABLED" | "LEGAL_CORPUS_MULTILINGUAL_ENABLED" | "LEGAL_CORPUS_OWNER_UPLOAD_AUTO_TRUST" | "LEGAL_CORPUS_USER_UPLOAD_AUTO_TRUST" | "LEGAL_CORPUS_HISTORICAL_ENABLED" | "LEGAL_CORPUS_DENSE_ENABLED" | "LEGAL_CORPUS_SHADOW_MODE" | "LEGAL_EVIDENCE_BUCKET_NAME" | "LEGAL_AI_SEARCH_NAMESPACE_NAME" | "LEGAL_AI_SEARCH_CONFIGURATION_ID" | "LEGAL_AI_GATEWAY_ID" | "LEGAL_AI_PROVIDER_PROJECT_ID" | "LEGAL_AI_SEARCH_EMBEDDING_MODEL" | "LEGAL_AI_SEARCH_DIMENSIONS" | "LEGAL_AI_SEARCH_KEYWORD_TOKENIZER" | "LEGAL_AI_SEARCH_METADATA_SCHEMA" | "LEGAL_AI_SEARCH_SOURCE_PREFIX" | "LEGAL_AI_SEARCH_MAX_RESULTS" | "LEGAL_AI_SEARCH_MAX_INSTANCES_PER_QUERY" | "LEGAL_AI_SEARCH_PAUSED" | "LEGAL_AI_SEARCH_GATEWAY_PAYLOAD_LOGGING" | "LEGAL_AI_SEARCH_GATEWAY_CACHE" | "LEGAL_AI_SEARCH_SIMILARITY_CACHE" | "QDRANT_URL" | "QDRANT_COLLECTION" | "LEGAL_CORPUS_INDEX_VERSION" | "EMBEDDING_MODEL" | "OPENAI_API_KEY" | "ANTHROPIC_API_KEY" | "OPENAI_MODEL" | "JURO_SMOKE_BASE_URL" | "RESEND_API_KEY" | "EMAIL_FROM">> {}
}
