/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.legal-custom-current.jsonc --include-runtime=false --strict-vars=false --env-interface=CustomCurrentBindings worker/legal-custom-current-env.d.ts` (hash: d4cfa4ee583eb60d037102473b651a69)
interface __BaseEnv_CustomCurrentBindings {
	REUSABLE_ARTIFACTS: R2Bucket;
	EVIDENCE: R2Bucket;
	ARTIFACTS: R2Bucket;
	SOURCE_DB: D1Database;
	LEGAL_DB: D1Database;
	CATALOG_DB: D1Database;
	DENSE: VectorizeIndex;
	BUILD_QUEUE: Queue;
	AI: Ai;
	APP_ENV: string;
	AI_GATEWAY_ID: string;
	DOCUMENT_EMBEDDINGS_ENABLED: string;
	ACCEPTED_INPUT_MANIFEST_KEY: string;
	ACCEPTED_INPUT_MANIFEST_SHA256: string;
	OPENAI_REQUESTS_PER_MINUTE: string;
	OPENAI_TOKENS_PER_MINUTE: string;
	AUTHORIZED_PROVIDER_TOKENS: string;
	AUTHORIZED_EMBEDDING_RECONCILIATION_SHA256: string;
	CUSTOM_SEARCH_CAPABILITY: string;
	CUSTOM_SEARCH_RELEASE_ID: string;
	CUSTOM_SEARCH_INSTANCE_ID: string;
	CUSTOM_SEARCH_SHARD_ID: string;
	CUSTOM_RUNTIME_DESCRIPTOR_KEY: string;
	CUSTOM_RUNTIME_DESCRIPTOR_SHA256: string;
	OPENAI_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	OPENAI_MODEL: string;
	JURO_SMOKE_BASE_URL: string;
	RESEND_API_KEY: string;
	EMAIL_FROM: string;
	COORDINATOR: DurableObjectNamespace<import("./legal-custom-current-build-worker").CustomCurrentBuildCoordinator>;
	REDUCER: DurableObjectNamespace<import("./legal-custom-current-build-worker").CustomCurrentBm25ReducerContainer>;
	BUILD_WORKFLOW: Workflow<Parameters<import("./legal-custom-current-build-worker").CustomCurrentBuildWorkflow['run']>[0]['payload']>;
	REDUCE_WORKFLOW: Workflow<Parameters<import("./legal-custom-current-build-worker").CustomCurrentReduceWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./legal-custom-current-build-worker");
		durableNamespaces: "CustomCurrentBuildCoordinator" | "CustomCurrentBm25ReducerContainer";
	}
	interface Env extends __BaseEnv_CustomCurrentBindings {}
}
// Keep this file module-scoped: this is not the application Worker's Env.
export interface CustomCurrentBindings extends __BaseEnv_CustomCurrentBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "AI_GATEWAY_ID" | "DOCUMENT_EMBEDDINGS_ENABLED" | "ACCEPTED_INPUT_MANIFEST_KEY" | "ACCEPTED_INPUT_MANIFEST_SHA256" | "OPENAI_REQUESTS_PER_MINUTE" | "OPENAI_TOKENS_PER_MINUTE" | "AUTHORIZED_PROVIDER_TOKENS" | "AUTHORIZED_EMBEDDING_RECONCILIATION_SHA256" | "CUSTOM_SEARCH_CAPABILITY" | "CUSTOM_SEARCH_RELEASE_ID" | "CUSTOM_SEARCH_INSTANCE_ID" | "CUSTOM_SEARCH_SHARD_ID" | "CUSTOM_RUNTIME_DESCRIPTOR_KEY" | "CUSTOM_RUNTIME_DESCRIPTOR_SHA256" | "OPENAI_API_KEY" | "ANTHROPIC_API_KEY" | "OPENAI_MODEL" | "JURO_SMOKE_BASE_URL" | "RESEND_API_KEY" | "EMAIL_FROM">> {}
}
