/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.legal-corpus.jsonc --include-runtime=false --env-interface=LegalCorpusDevelopmentEnv worker/legal-corpus-development-configuration.d.ts` (hash: c90389e18ff73efcaba40bbb8ad0a6e7)
interface __BaseEnv_LegalCorpusDevelopmentEnv {
	LEGAL_EVIDENCE_BUCKET: R2Bucket;
	LEGAL_CUSTOM_ARTIFACT_BUCKET?: R2Bucket;
	LEGAL_DB: D1Database;
	APP_ENV: "staging" | "production" | "development";
	LEGAL_CORPUS_LEGACY_WRITES_ENABLED: "false";
	LEGAL_CORPUS_SHADOW_MODE: "true" | "false";
	LEGAL_EVIDENCE_BUCKET_NAME: "juro-legal-evidence-staging-green2-20260831" | "juro-legal-evidence-production-20260908" | "juro-legal-evidence-development";
	LEGAL_AI_GATEWAY_ID: "juro-ai-search-staging" | "juro-ai-search-production" | "juro-ai-search-development";
	LEGAL_AI_PROVIDER_PROJECT_ID: "juro-openai-staging" | "juro-openai-production" | "juro-openai-development";
	OPENAI_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	OPENAI_MODEL: string;
	JURO_SMOKE_BASE_URL: string;
	RESEND_API_KEY: string;
	EMAIL_FROM: string;
	LEGAL_CORPUS_REASONING_SERVICE: Fetcher /* juro-platform-staging */ | Fetcher /* juro */ | Fetcher /* juro-platform-development */;
	LEGAL_CUSTOM_SEARCH_SERVICE?: Fetcher /* juro-legal-current-custom-pair-20260906 */ | Fetcher /* juro-legal-current-search-production-20260909 */;
	LEGAL_CUSTOM_HISTORY_SEARCH_SERVICE?: Fetcher /* juro-legal-history-custom-20260906 */ | Fetcher /* juro-legal-history-custom-production-20260908 */;
	LEGAL_HISTORY_EVIDENCE_BUCKET?: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./legal-corpus-worker");
	}
	interface StagingEnv {
		LEGAL_EVIDENCE_BUCKET: R2Bucket;
		LEGAL_CUSTOM_ARTIFACT_BUCKET: R2Bucket;
		LEGAL_DB: D1Database;
		APP_ENV: "staging";
		LEGAL_CORPUS_LEGACY_WRITES_ENABLED: "false";
		LEGAL_CORPUS_SHADOW_MODE: "true";
		LEGAL_EVIDENCE_BUCKET_NAME: "juro-legal-evidence-staging-green2-20260831";
		LEGAL_AI_GATEWAY_ID: "juro-ai-search-staging";
		LEGAL_AI_PROVIDER_PROJECT_ID: "juro-openai-staging";
		OPENAI_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		OPENAI_MODEL: string;
		JURO_SMOKE_BASE_URL: string;
		RESEND_API_KEY: string;
		EMAIL_FROM: string;
		LEGAL_CORPUS_REASONING_SERVICE: Fetcher /* juro-platform-staging */;
		LEGAL_CUSTOM_SEARCH_SERVICE: Fetcher /* juro-legal-current-custom-pair-20260906 */;
		LEGAL_CUSTOM_HISTORY_SEARCH_SERVICE: Fetcher /* juro-legal-history-custom-20260906 */;
	}
	interface ProductionEnv {
		LEGAL_EVIDENCE_BUCKET: R2Bucket;
		LEGAL_HISTORY_EVIDENCE_BUCKET: R2Bucket;
		LEGAL_CUSTOM_ARTIFACT_BUCKET: R2Bucket;
		LEGAL_DB: D1Database;
		APP_ENV: "production";
		LEGAL_CORPUS_LEGACY_WRITES_ENABLED: "false";
		LEGAL_CORPUS_SHADOW_MODE: "false";
		LEGAL_EVIDENCE_BUCKET_NAME: "juro-legal-evidence-production-20260908";
		LEGAL_AI_GATEWAY_ID: "juro-ai-search-production";
		LEGAL_AI_PROVIDER_PROJECT_ID: "juro-openai-production";
		OPENAI_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		OPENAI_MODEL: string;
		JURO_SMOKE_BASE_URL: string;
		RESEND_API_KEY: string;
		EMAIL_FROM: string;
		LEGAL_CORPUS_REASONING_SERVICE: Fetcher /* juro */;
		LEGAL_CUSTOM_SEARCH_SERVICE: Fetcher /* juro-legal-current-search-production-20260909 */;
		LEGAL_CUSTOM_HISTORY_SEARCH_SERVICE: Fetcher /* juro-legal-history-custom-production-20260908 */;
	}
	interface Env extends __BaseEnv_LegalCorpusDevelopmentEnv {}
}
interface LegalCorpusDevelopmentEnv extends __BaseEnv_LegalCorpusDevelopmentEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "LEGAL_CORPUS_LEGACY_WRITES_ENABLED" | "LEGAL_CORPUS_SHADOW_MODE" | "LEGAL_EVIDENCE_BUCKET_NAME" | "LEGAL_AI_GATEWAY_ID" | "LEGAL_AI_PROVIDER_PROJECT_ID" | "OPENAI_API_KEY" | "ANTHROPIC_API_KEY" | "OPENAI_MODEL" | "JURO_SMOKE_BASE_URL" | "RESEND_API_KEY" | "EMAIL_FROM">> {}
}
