/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.legal-corpus.jsonc --include-runtime=false --env-interface=LegalCorpusDevelopmentEnv worker/legal-corpus-development-configuration.d.ts` (hash: 5e3bfe2692b535afc2905936d4a63db0)
interface __BaseEnv_LegalCorpusDevelopmentEnv {
	BUCKET: R2Bucket;
	BACKUP_BUCKET: R2Bucket;
	LEGAL_EVIDENCE_BUCKET: R2Bucket;
	DB: D1Database;
	LEGAL_DB: D1Database;
	APP_ENV: "staging" | "production" | "development";
	LEGAL_CORPUS_ENABLED: "true" | "false";
	LEGAL_CORPUS_AUTO_INGEST_ENABLED: "true" | "false";
	LEGAL_CORPUS_LIVE_LEXUZ_ENABLED: "true" | "false";
	LEGAL_CORPUS_MULTILINGUAL_ENABLED: "true" | "false";
	LEGAL_CORPUS_OWNER_UPLOAD_AUTO_TRUST: "true" | "false";
	LEGAL_CORPUS_USER_UPLOAD_AUTO_TRUST: "true" | "false";
	LEGAL_CORPUS_HISTORICAL_ENABLED: "true" | "false";
	LEGAL_CORPUS_DENSE_ENABLED: "true" | "false";
	LEGAL_CORPUS_SHADOW_MODE: "true" | "false";
	LEGAL_EVIDENCE_BUCKET_NAME: "juro-legal-evidence-staging" | "juro-legal-evidence-production" | "juro-legal-evidence-development";
	QDRANT_URL?: "https://qdrant.internal";
	QDRANT_COLLECTION?: "juro_legal_staging_provision_v1";
	LEGAL_CORPUS_INDEX_VERSION?: "staging-20260830-provision-v1";
	EMBEDDING_MODEL?: "text-embedding-3-large";
	OPENAI_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	OPENAI_MODEL: string;
	JURO_SMOKE_BASE_URL: string;
	RESEND_API_KEY: string;
	EMAIL_FROM: string;
	QDRANT_SERVICE?: Fetcher /* juro-platform-staging */;
	LEGAL_CORPUS_EMBEDDING_SERVICE?: Fetcher /* juro-platform-staging */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./legal-corpus-worker");
	}
	interface StagingEnv {
		BUCKET: R2Bucket;
		BACKUP_BUCKET: R2Bucket;
		LEGAL_EVIDENCE_BUCKET: R2Bucket;
		DB: D1Database;
		LEGAL_DB: D1Database;
		APP_ENV: "staging";
		LEGAL_CORPUS_ENABLED: "true";
		LEGAL_CORPUS_AUTO_INGEST_ENABLED: "true";
		LEGAL_CORPUS_LIVE_LEXUZ_ENABLED: "true";
		LEGAL_CORPUS_MULTILINGUAL_ENABLED: "true";
		LEGAL_CORPUS_OWNER_UPLOAD_AUTO_TRUST: "true";
		LEGAL_CORPUS_USER_UPLOAD_AUTO_TRUST: "true";
		LEGAL_CORPUS_HISTORICAL_ENABLED: "true";
		LEGAL_CORPUS_DENSE_ENABLED: "true";
		LEGAL_CORPUS_SHADOW_MODE: "true";
		LEGAL_EVIDENCE_BUCKET_NAME: "juro-legal-evidence-staging";
		QDRANT_URL: "https://qdrant.internal";
		QDRANT_COLLECTION: "juro_legal_staging_provision_v1";
		LEGAL_CORPUS_INDEX_VERSION: "staging-20260830-provision-v1";
		EMBEDDING_MODEL: "text-embedding-3-large";
		OPENAI_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		OPENAI_MODEL: string;
		JURO_SMOKE_BASE_URL: string;
		RESEND_API_KEY: string;
		EMAIL_FROM: string;
		QDRANT_SERVICE: Fetcher /* juro-platform-staging */;
		LEGAL_CORPUS_EMBEDDING_SERVICE: Fetcher /* juro-platform-staging */;
	}
	interface ProductionEnv {
		BUCKET: R2Bucket;
		BACKUP_BUCKET: R2Bucket;
		LEGAL_EVIDENCE_BUCKET: R2Bucket;
		DB: D1Database;
		LEGAL_DB: D1Database;
		APP_ENV: "production";
		LEGAL_CORPUS_ENABLED: "false";
		LEGAL_CORPUS_AUTO_INGEST_ENABLED: "false";
		LEGAL_CORPUS_LIVE_LEXUZ_ENABLED: "false";
		LEGAL_CORPUS_MULTILINGUAL_ENABLED: "false";
		LEGAL_CORPUS_OWNER_UPLOAD_AUTO_TRUST: "false";
		LEGAL_CORPUS_USER_UPLOAD_AUTO_TRUST: "false";
		LEGAL_CORPUS_HISTORICAL_ENABLED: "false";
		LEGAL_CORPUS_DENSE_ENABLED: "false";
		LEGAL_CORPUS_SHADOW_MODE: "false";
		LEGAL_EVIDENCE_BUCKET_NAME: "juro-legal-evidence-production";
		OPENAI_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		OPENAI_MODEL: string;
		JURO_SMOKE_BASE_URL: string;
		RESEND_API_KEY: string;
		EMAIL_FROM: string;
	}
	interface Env extends __BaseEnv_LegalCorpusDevelopmentEnv {}
}
interface LegalCorpusDevelopmentEnv extends __BaseEnv_LegalCorpusDevelopmentEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "LEGAL_CORPUS_ENABLED" | "LEGAL_CORPUS_AUTO_INGEST_ENABLED" | "LEGAL_CORPUS_LIVE_LEXUZ_ENABLED" | "LEGAL_CORPUS_MULTILINGUAL_ENABLED" | "LEGAL_CORPUS_OWNER_UPLOAD_AUTO_TRUST" | "LEGAL_CORPUS_USER_UPLOAD_AUTO_TRUST" | "LEGAL_CORPUS_HISTORICAL_ENABLED" | "LEGAL_CORPUS_DENSE_ENABLED" | "LEGAL_CORPUS_SHADOW_MODE" | "LEGAL_EVIDENCE_BUCKET_NAME" | "QDRANT_URL" | "QDRANT_COLLECTION" | "LEGAL_CORPUS_INDEX_VERSION" | "EMBEDDING_MODEL" | "OPENAI_API_KEY" | "ANTHROPIC_API_KEY" | "OPENAI_MODEL" | "JURO_SMOKE_BASE_URL" | "RESEND_API_KEY" | "EMAIL_FROM">> {}
}
