import {
  LEGAL_CORPUS_STAGING_D1_DATABASE_NAME,
  legalCorpusReleaseEvidenceSchema,
  type LegalCorpusReleaseEvidence,
} from "../../lib/legal-corpus/release-gate";
import {
  LEX_CORPUS_CATEGORIES,
  LEX_CORPUS_LANGUAGES,
} from "../../lib/legal-corpus/lex-discovery";

export const LEGAL_CORPUS_TEST_NOW = new Date("2026-08-15T12:00:00.000Z");
export const LEGAL_CORPUS_TEST_COMMIT = "a".repeat(40);
export const LEGAL_CORPUS_TEST_SNAPSHOT = "b".repeat(64);

export function validLegalCorpusReleaseEvidence(): LegalCorpusReleaseEvidence {
  return legalCorpusReleaseEvidenceSchema.parse({
    schemaVersion: 5,
    environment: "staging",
    capturedAt: "2026-08-15T11:58:00.000Z",
    applicationCommit: LEGAL_CORPUS_TEST_COMMIT,
    corpusSnapshotSha256: LEGAL_CORPUS_TEST_SNAPSHOT,
    humanReview: {
      schemaVersion: 1,
      corpusVersion: "2026-08-13.1",
      corpusSha256: "c".repeat(64),
      evaluationRunId: "staging-20260814-canonical",
      attestationId: "22000000-0000-4000-8000-000000000001",
      attestationEventHash: "d".repeat(64),
      scopeDigest: "e".repeat(64),
      exportDigest: "f".repeat(64),
      fileSha256: "1".repeat(64),
      recordCount: 314,
      correctCount: 314,
      reviewerMfaVerifiedAt: "2026-08-15T11:55:00.000Z",
      exportedAt: "2026-08-15T11:57:00.000Z",
      verified: true,
    },
    d1Capacity: {
      schemaVersion: 1,
      environment: "staging",
      databaseId: "62620fb3-3da3-4c76-a8e9-aa60858c1063",
      databaseName: LEGAL_CORPUS_STAGING_D1_DATABASE_NAME,
      observedAt: "2026-08-15T11:59:00.000Z",
      databaseSizeBytes: 2_862_432_256,
      source: "wrangler_d1_info",
      fileSha256: "3".repeat(64),
    },
    dashboard: {
      environment: "staging",
      featureFlags: {
        LEGAL_CORPUS_ENABLED: true,
        LEGAL_CORPUS_LIVE_LEXUZ_ENABLED: true,
        LEGAL_CORPUS_AUTO_INGEST_ENABLED: false,
        LEGAL_CORPUS_MULTILINGUAL_ENABLED: true,
        LEGAL_CORPUS_OWNER_UPLOAD_AUTO_TRUST: true,
        LEGAL_CORPUS_USER_UPLOAD_AUTO_TRUST: true,
        LEGAL_CORPUS_HISTORICAL_ENABLED: true,
        LEGAL_CORPUS_DENSE_ENABLED: true,
        LEGAL_CORPUS_SHADOW_MODE: true,
      },
      lexHealth: { state: "fresh" },
      qdrantHealth: {
        configured: true,
        enabled: true,
        status: "ready",
        totalPoints: 25_000,
        currentPoints: 22_513,
        errorCode: null,
        checkedAt: "2026-08-15T11:59:00.000Z",
      },
      totals: {
        canonicalDocuments: 1_500,
        languageVariants: 2_400,
        uniqueProvisions: 22_000,
        currentProvisions: 22_000,
        currentChunks: 22_513,
        indexedChunks: 22_513,
        activeDocuments: 1_400,
        repealedDocuments: 100,
        historicalVersions: 3_000,
        documentsFetchedToday: 50,
        liveOrManualQueued: 0,
        failedDocuments: 0,
        lastSuccessfulUpdate: "2026-08-15T11:55:00.000Z",
      },
      coverage: LEX_CORPUS_CATEGORIES.flatMap(({ key }) =>
        LEX_CORPUS_LANGUAGES.map(({ language }) => ({
          categoryKey: key,
          language,
          status: "completed",
          expectedDocuments: 100,
          discoveredDocuments: 100,
          fetchedDocuments: 100,
          extractedDocuments: 100,
          indexedDocuments: 100,
          technicallyUnavailable: 0,
          pageNumber: 5,
          lastErrorCode: null,
          updatedAt: "2026-08-15T11:55:00.000Z",
          complete: true,
        })),
      ),
      failures: [],
      integrity: { valid: true, checked: 2 },
    },
    benchmark: {
      generatedAt: "2026-08-15T11:59:00.000Z",
      applicationCommit: LEGAL_CORPUS_TEST_COMMIT,
      corpusSnapshotSha256: LEGAL_CORPUS_TEST_SNAPSHOT,
      scenarioCount: 314,
      reviewedScenarioCount: 314,
      providerRequestCount: 628,
      unpricedRequestCount: 0,
      totalProviderCostUsd: 12.5,
      identicalSourcePackets: true,
      officialOnly: true,
      denseEnabled: true,
      sparseEnabled: true,
      rrfEnabled: true,
      qdrantVectorSize: 1536,
      qdrantDistance: "Cosine",
      qdrantCurrentPointCount: 22_513,
      qdrantTotalPointCount: 25_000,
      qdrantSnapshotSha256: "2".repeat(64),
      qdrantSnapshotCurrentPointCount: 22_513,
      qdrantSnapshotTotalPointCount: 25_000,
      rerankMode: "deterministic",
      recallAt5: 0.94,
      recallAt10: 0.97,
      mrr: 0.9,
      citationPrecision: 1,
      citationRecall: 0.97,
      articleExactness: 0.97,
      documentExactness: 0.99,
      abstentionAccuracy: 0.97,
      partialAnswerAccuracy: 0.94,
      staleSourceRate: 0,
      invalidLinkRate: 0,
      groundedness: 0.98,
      p95RetrievalMs: 2_500,
      p95CompleteAnswerMs: 21_000,
    },
  });
}
