"use client";
import { RefreshCw, Send, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent } from "react";
type Locale="ru"|"uz"; type Ticket={id:string;subject:string;category:string;severity:string;status:"open"|"waiting_user"|"resolved"}; type Message={id:string;authorType:"requester"|"staff";body:string};
const copy={ru:{title:"Обращения в поддержку",refresh:"Обновить",reply:"Ответ",send:"Отправить",empty:"Обращений нет",status:"Статус"},uz:{title:"Qo‘llab-quvvatlash murojaatlari",refresh:"Yangilash",reply:"Javob",send:"Yuborish",empty:"Murojaatlar yo‘q",status:"Holat"}} as const;
async function json<T>(response:Response){const body=await response.json() as T&{error?:string};if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);return body;}
export function SupportInbox({locale,staffName}:{locale:Locale;staffName:string}){
 const t=copy[locale];const [tickets,setTickets]=useState<Ticket[]>([]);const [selected,setSelected]=useState<Ticket|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState("");const [status,setStatus]=useState<Ticket["status"]>("open");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);try{setTickets((await json<{tickets:Ticket[]}>(await fetch("/api/platform/admin/support-tickets",{cache:"no-store"}))).tickets);setError("");}catch(e){setError(e instanceof Error?e.message:"ERROR");}finally{setBusy(false);}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 async function open(ticket:Ticket){setBusy(true);try{const data=await json<{ticket:Ticket;messages:Message[]}>(await fetch(`/api/platform/admin/support-tickets/${ticket.id}`));setSelected(data.ticket);setMessages(data.messages);setStatus(data.ticket.status);}catch(e){setError(e instanceof Error?e.message:"ERROR");}finally{setBusy(false);}}
 async function submit(event:FormEvent){event.preventDefault();if(!selected||!text.trim())return;setBusy(true);try{await json(await fetch(`/api/platform/admin/support-tickets/${selected.id}`,{method:"POST",headers:{"content-type":"application/json","x-juro-csrf":"1"},body:JSON.stringify({body:text.trim(),status})}));setText("");await open(selected);await load();}catch(e){setError(e instanceof Error?e.message:"ERROR");}finally{setBusy(false);}}
 return <div className="staff-console"><header className="staff-topbar"><div className="staff-brand"><ShieldCheck/><span><b>JURO</b><small>SUPPORT OPERATIONS</small></span></div><div className="staff-session"><span>Fresh 2FA</span><b>{staffName}</b></div></header><main className="staff-main"><section className="staff-heading"><h1>{t.title}</h1><button onClick={()=>void load()} disabled={busy}><RefreshCw/>{t.refresh}</button></section>{error&&<p className="staff-error">{error}</p>}<section className="staff-queue">{tickets.length?tickets.map(ticket=><article className="staff-table-row" key={ticket.id}><div className="staff-source"><span>{ticket.severity}</span><b>{ticket.subject}</b><small>{ticket.category}</small></div><div className={`staff-status status-${ticket.status}`}>{ticket.status}</div><div className="staff-row-actions"><button onClick={()=>void open(ticket)} disabled={busy}>{t.reply}</button></div></article>):<p className="staff-empty">{t.empty}</p>}</section>{selected&&<form className="staff-decision" onSubmit={event=>void submit(event)}><h2>{selected.subject}</h2>{messages.map(message=><p key={message.id}><b>{message.authorType}</b>: {message.body}</p>)}<label>{t.reply}<textarea required value={text} onChange={event=>setText(event.target.value)}/></label><label>{t.status}<select value={status} onChange={event=>setStatus(event.target.value as Ticket["status"])}><option value="open">open</option><option value="waiting_user">waiting_user</option><option value="resolved">resolved</option></select></label><button className="staff-approve" disabled={busy||!text.trim()}><Send/>{t.send}</button></form>}</main></div>;
}
