import type { PlatformLocale } from "../lib/platform/routing";

const localeValue = <T>(locale: PlatformLocale, value: { ru: T; uz: T }): T => value[locale];

const dashboard = {
  greeting: { ru: "Добрый день", uz: "Xayrli kun" },
  question: { ru: "Что нужно решить сегодня?", uz: "Bugun nimani hal qilish kerak?" },
  prompt: {
    ru: "Опишите ситуацию или задайте юридический вопрос",
    uz: "Vaziyatni yozing yoki yuridik savol bering",
  },
  attach: { ru: "Прикрепить документ", uz: "Hujjat biriktirish" },
  removeFile: { ru: "Убрать файл", uz: "Faylni olib tashlash" },
  send: { ru: "Начать", uz: "Boshlash" },
  consent: {
    ru: "Согласен(на) на приватную загрузку и автоматизированный анализ выбранного файла.",
    uz: "Tanlangan faylni maxfiy yuklash va avtomatlashtirilgan tahlilga roziman.",
  },
  contextPersonal: { ru: "Личное пространство", uz: "Shaxsiy makon" },
  contextBusiness: { ru: "Бизнес-пространство", uz: "Biznes makoni" },
  quickTitle: { ru: "Быстрый запуск", uz: "Tezkor boshlash" },
  continueTitle: { ru: "Продолжить работу", uz: "Ishni davom ettirish" },
  attentionTitle: { ru: "Требует внимания", uz: "E’tibor talab qiladi" },
  recentTitle: { ru: "Последние материалы", uz: "So‘nggi materiallar" },
  emptyAttention: {
    ru: "Срочных действий нет. Новые сроки, анализы и комментарии появятся здесь.",
    uz: "Shoshilinch harakatlar yo‘q. Yangi muddatlar, tahlillar va izohlar shu yerda ko‘rinadi.",
  },
  emptyRecent: {
    ru: "Создайте дело или документ — JURO сохранит контекст и следующий шаг.",
    uz: "Ish yoki hujjat yarating — JURO kontekst va keyingi qadamni saqlaydi.",
  },
  openAll: { ru: "Открыть все", uz: "Barchasini ochish" },
  refresh: { ru: "Обновить рабочее пространство", uz: "Ish makonini yangilash" },
  fileTooLarge: { ru: "Файл превышает 10 МБ.", uz: "Fayl 10 MB dan katta." },
  loadError: { ru: "Не удалось загрузить рабочее пространство.", uz: "Ish makonini yuklab bo‘lmadi." },
  uploadError: { ru: "Файл не удалось загрузить.", uz: "Faylni yuklab bo‘lmadi." },
  journeyLabel: { ru: "Золотой юридический маршрут JURO", uz: "JURO oltin yuridik yo‘li" },
  journeySteps: {
    ru: ["Вопрос", "Источники", "Анализ", "Действие"],
    uz: ["Savol", "Manbalar", "Tahlil", "Harakat"],
  },
  actions: {
    ask: {
      title: { ru: "Задать вопрос AI-юристу", uz: "AI-yuristga savol berish" },
      description: { ru: "Отделим факты от предположений и предложим следующий шаг.", uz: "Faktlarni taxminlardan ajratib, keyingi qadamni taklif qilamiz." },
    },
    review: {
      title: { ru: "Проверить документ на риски", uz: "Hujjat xavflarini tekshirish" },
      description: { ru: "Покажем спорные условия, пробелы и вопросы для проверки.", uz: "Bahsli shartlar, bo‘shliqlar va tekshiruv savollarini ko‘rsatamiz." },
    },
    compare: {
      title: { ru: "Сравнить две версии", uz: "Ikki versiyani taqqoslash" },
      description: { ru: "Найдём добавления, удаления и изменение вашего риска.", uz: "Qo‘shish, olib tashlash va xavf o‘zgarishini topamiz." },
    },
    create: {
      title: { ru: "Создать документ", uz: "Hujjat yaratish" },
      description: { ru: "Соберём проект по шагам и сохраним редактируемую версию.", uz: "Loyihani bosqichma-bosqich tuzib, tahrirlanadigan versiyani saqlaymiz." },
    },
    plan: {
      title: { ru: "Составить план действий", uz: "Harakatlar rejasini tuzish" },
      description: { ru: "Свяжем задачу, сроки, документы и ответственных.", uz: "Vazifa, muddat, hujjat va mas’ullarni bog‘laymiz." },
    },
    lawyer: {
      title: { ru: "Передать живому юристу", uz: "Jonli yuristga topshirish" },
      description: { ru: "Передадим только выбранный вами контекст и документы.", uz: "Faqat siz tanlagan kontekst va hujjatlarni yuboramiz." },
    },
  },
} as const;

export function dashboardCopy(locale: PlatformLocale) {
  return {
    greeting: localeValue(locale, dashboard.greeting),
    question: localeValue(locale, dashboard.question),
    prompt: localeValue(locale, dashboard.prompt),
    attach: localeValue(locale, dashboard.attach),
    removeFile: localeValue(locale, dashboard.removeFile),
    send: localeValue(locale, dashboard.send),
    consent: localeValue(locale, dashboard.consent),
    contextPersonal: localeValue(locale, dashboard.contextPersonal),
    contextBusiness: localeValue(locale, dashboard.contextBusiness),
    quickTitle: localeValue(locale, dashboard.quickTitle),
    continueTitle: localeValue(locale, dashboard.continueTitle),
    attentionTitle: localeValue(locale, dashboard.attentionTitle),
    recentTitle: localeValue(locale, dashboard.recentTitle),
    emptyAttention: localeValue(locale, dashboard.emptyAttention),
    emptyRecent: localeValue(locale, dashboard.emptyRecent),
    openAll: localeValue(locale, dashboard.openAll),
    refresh: localeValue(locale, dashboard.refresh),
    fileTooLarge: localeValue(locale, dashboard.fileTooLarge),
    loadError: localeValue(locale, dashboard.loadError),
    uploadError: localeValue(locale, dashboard.uploadError),
    journeyLabel: localeValue(locale, dashboard.journeyLabel),
    journeySteps: dashboard.journeySteps[locale],
    actions: Object.fromEntries(Object.entries(dashboard.actions).map(([key, value]) => [
      key,
      {
        title: localeValue(locale, value.title),
        description: localeValue(locale, value.description),
      },
    ])) as Record<keyof typeof dashboard.actions, { title: string; description: string }>,
  };
}

export const comparisonText = {
  ru: {
    tool: "Анализ документов",
    title: "Проверяйте риски и сравнивайте редакции",
    description: "JURO хранит исходные версии неизменяемыми и отделяет точный redline от юридической AI-оценки.",
    singleMode: "Проверить один документ",
    compareMode: "Сравнить две версии",
    versionOne: "Версия 1 · исходный документ",
    versionTwo: "Версия 2 · новая редакция",
    chooseFile: "Перетащите файл или выберите на устройстве",
    chooseStored: "Или выберите сохранённый файл",
    replace: "Заменить",
    remove: "Удалить",
    swap: "Поменять версии местами",
    consent: "Согласен(на) на приватное сохранение и автоматизированное сравнение выбранных версий.",
    start: "Начать сравнение",
    supported: "PDF или DOCX до 10 МБ. Для сканов требуется подключённый OCR.",
    recent: "Сохранённые сравнения",
    noComparisons: "Сравнений пока нет.",
    identicalWarning: "Файлы идентичны по SHA-256; JURO всё равно подтвердит отсутствие изменений.",
    differentWarning: "Документы существенно различаются и могут не быть версиями друг друга.",
    processing: "Сравнение выполняется",
    stages: {
      uploaded: "Загрузка",
      extracting_version_one: "Извлечение текста версии 1",
      extracting_version_two: "Извлечение текста версии 2",
      structuring: "Распознавание структуры",
      diffing: "Точный поиск изменений",
      legal_analysis: "Анализ изменения рисков",
      completed: "Готово",
      failed: "Ошибка",
    },
    retry: "Повторить неудавшийся этап",
    open: "Открыть результат",
  },
  uz: {
    tool: "Hujjatlarni tahlil qilish",
    title: "Xavflarni tekshiring va tahrirlarni taqqoslang",
    description: "JURO asl versiyalarni o‘zgarmas holda saqlaydi va aniq redline’ni yuridik AI-bahodan ajratadi.",
    singleMode: "Bitta hujjatni tekshirish",
    compareMode: "Ikki versiyani taqqoslash",
    versionOne: "1-versiya · dastlabki hujjat",
    versionTwo: "2-versiya · yangi tahrir",
    chooseFile: "Faylni tashlang yoki qurilmadan tanlang",
    chooseStored: "Yoki saqlangan faylni tanlang",
    replace: "Almashtirish",
    remove: "Olib tashlash",
    swap: "Versiyalarni joyini almashtirish",
    consent: "Tanlangan versiyalarni maxfiy saqlash va avtomatlashtirilgan taqqoslashga roziman.",
    start: "Taqqoslashni boshlash",
    supported: "10 MB gacha PDF yoki DOCX. Skanlar uchun ulangan OCR talab qilinadi.",
    recent: "Saqlangan taqqoslashlar",
    noComparisons: "Hozircha taqqoslashlar yo‘q.",
    identicalWarning: "Fayllar SHA-256 bo‘yicha bir xil; JURO o‘zgarish yo‘qligini baribir tasdiqlaydi.",
    differentWarning: "Hujjatlar keskin farq qiladi va bir hujjatning versiyalari bo‘lmasligi mumkin.",
    processing: "Taqqoslash bajarilmoqda",
    stages: {
      uploaded: "Yuklash",
      extracting_version_one: "1-versiya matnini ajratish",
      extracting_version_two: "2-versiya matnini ajratish",
      structuring: "Tuzilmani aniqlash",
      diffing: "Aniq o‘zgarishlarni qidirish",
      legal_analysis: "Xavf o‘zgarishini tahlil qilish",
      completed: "Tayyor",
      failed: "Xato",
    },
    retry: "Muvaffaqiyatsiz bosqichni takrorlash",
    open: "Natijani ochish",
  },
} as const;

export const comparisonResultText = {
  ru: {
    back: "Анализ документов",
    generated: "Анализ сформирован",
    uploaded: "Загружено",
    pages: "страниц",
    size: "Размер",
    documentLanguage: "Язык",
    recognition: "Распознавание",
    openVersion: "Открыть версию",
    qualityGood: "Текст извлечён",
    qualityLimited: "Ограниченная точность",
    qualityOcr: "Требуется OCR",
    partial: "Точный redline готов; юридическая AI-оценка доступна частично",
    retry: "Повторить обработку",
    delete: "Удалить сравнение",
    deleteConfirm: "Удалить сравнение? Оно исчезнет из рабочего пространства согласно политике хранения.",
    exportPdf: "Скачать PDF-отчёт",
    exportDocx: "Скачать DOCX redline",
    consult: "Передать юристу",
    edit: "Открыть конструктор",
    saveToCase: "Сохранить в дело",
    chooseCase: "Выберите дело",
    caseSaved: "Сравнение связано с делом",
    noCases: "Дел пока нет",
    createCase: "Создать дело",
    tabs: {
      summary: "Кратко",
      all: "Все изменения",
      side: "Две версии рядом",
      redline: "Redline",
      risks: "Изменение рисков",
      sources: "Источники",
      recommendations: "Рекомендации",
    },
    metrics: {
      changes: "изменений",
      material: "существенных",
      increased: "повышают риск",
      decreased: "снижают риск",
      similarity: "сходство версий",
    },
    overallRisk: "Общий уровень риска",
    changedSections: "Изменённые разделы",
    noChangedSections: "Названия разделов не распознаны.",
    likelyDifferent: "Документы существенно различаются и могут не быть версиями друг друга. Результат сохранён, но требует особенно внимательной проверки.",
    aiUnavailable: "AI-провайдер не подключён или временно недоступен. Точный diff выполнен, но юридический эффект отмечен как требующий проверки.",
    sourceUnavailable: "Источник временно не проверен",
    sourceUnavailableDetail: "Для этого вывода нет подтверждённого акта в серверном реестре JURO.",
    filters: "Фильтры",
    onlyMaterial: "Только существенные",
    increased: "Риск повысился",
    decreased: "Риск снизился",
    added: "Добавлено",
    removed: "Удалено",
    changed: "Изменено",
    moved: "Перемещено",
    renumbered: "Перенумеровано",
    formatting: "Только форматирование",
    hasSource: "Есть источник",
    lowConfidence: "Уверенность ниже 70%",
    sectionFilter: "Раздел документа",
    allSections: "Все разделы",
    partyFilter: "Затронутая сторона",
    allParties: "Все стороны",
    clearFilters: "Сбросить",
    noResults: "По выбранным фильтрам изменений нет.",
    before: "Было",
    after: "Стало",
    legalEffect: "Юридическое значение",
    affectedParty: "Затронутая сторона",
    recommendation: "Рекомендация",
    confidence: "Уверенность AI",
    reviewed: "Просмотрено",
    markReviewed: "Отметить просмотренным",
    syncScroll: "Синхронная прокрутка",
    versionOne: "Версия 1",
    versionTwo: "Версия 2",
    showVersion: "Показать",
    legend: "Легенда",
    unchanged: "Без изменений",
    noSources: "Подтверждённых источников пока нет.",
    officialSource: "Официальный источник",
    currentAsOf: "Актуальность проверена",
    originalLanguage: "Язык источника",
    status: "Статус",
    verified: "Проверен",
    processing: "Результат ещё формируется",
    extractionWarning: "Текст распознан с ограниченной точностью.",
    riskLabels: { high: "Высокий", medium: "Средний", low: "Низкий", information: "Информация" },
    changeLabels: {
      added: "Добавлено",
      removed: "Удалено",
      changed: "Изменено",
      moved: "Перемещено",
      renumbered: "Перенумеровано",
      formatting: "Форматирование",
      unchanged: "Без изменений",
    },
    effectLabels: {
      increased: "Риск повысился",
      decreased: "Риск снизился",
      neutral: "Нейтрально",
      requires_review: "Требует проверки",
      insufficient_data: "Недостаточно данных",
    },
  },
  uz: {
    back: "Hujjatlarni tahlil qilish",
    generated: "Tahlil yaratildi",
    uploaded: "Yuklangan",
    pages: "sahifa",
    size: "Hajmi",
    documentLanguage: "Til",
    recognition: "Tanib olish",
    openVersion: "Versiyani ochish",
    qualityGood: "Matn ajratildi",
    qualityLimited: "Aniqlik cheklangan",
    qualityOcr: "OCR talab qilinadi",
    partial: "Aniq redline tayyor; yuridik AI-baho qisman mavjud",
    retry: "Qayta ishlash",
    delete: "Taqqoslashni o‘chirish",
    deleteConfirm: "Taqqoslash o‘chirilsinmi? U saqlash siyosatiga muvofiq ish makonidan yo‘qoladi.",
    exportPdf: "PDF-hisobotni yuklash",
    exportDocx: "DOCX redline’ni yuklash",
    consult: "Yuristga topshirish",
    edit: "Konstruktorni ochish",
    saveToCase: "Ishga saqlash",
    chooseCase: "Ishni tanlang",
    caseSaved: "Taqqoslash ishga bog‘landi",
    noCases: "Hozircha ishlar yo‘q",
    createCase: "Ish yaratish",
    tabs: {
      summary: "Qisqacha",
      all: "Barcha o‘zgarishlar",
      side: "Ikki versiya yonma-yon",
      redline: "Redline",
      risks: "Xavf o‘zgarishi",
      sources: "Manbalar",
      recommendations: "Tavsiyalar",
    },
    metrics: {
      changes: "o‘zgarish",
      material: "muhim",
      increased: "xavfni oshiradi",
      decreased: "xavfni kamaytiradi",
      similarity: "versiyalar o‘xshashligi",
    },
    overallRisk: "Umumiy xavf darajasi",
    changedSections: "O‘zgargan bo‘limlar",
    noChangedSections: "Bo‘lim nomlari aniqlanmadi.",
    likelyDifferent: "Hujjatlar keskin farq qiladi va bir hujjatning versiyalari bo‘lmasligi mumkin. Natija saqlandi, ammo alohida e’tibor bilan tekshirish kerak.",
    aiUnavailable: "AI-provayder ulanmagan yoki vaqtincha ishlamaydi. Aniq diff bajarildi, ammo yuridik ta’sir tekshiruv talab qiladi.",
    sourceUnavailable: "Manba vaqtincha tekshirilmagan",
    sourceUnavailableDetail: "Bu xulosa uchun JURO server reyestrida tasdiqlangan hujjat yo‘q.",
    filters: "Filtrlar",
    onlyMaterial: "Faqat muhimlari",
    increased: "Xavf oshdi",
    decreased: "Xavf kamaydi",
    added: "Qo‘shilgan",
    removed: "Olib tashlangan",
    changed: "O‘zgartirilgan",
    moved: "Ko‘chirilgan",
    renumbered: "Qayta raqamlangan",
    formatting: "Faqat format",
    hasSource: "Manbasi bor",
    lowConfidence: "Ishonch 70% dan past",
    sectionFilter: "Hujjat bo‘limi",
    allSections: "Barcha bo‘limlar",
    partyFilter: "Ta’sirlangan tomon",
    allParties: "Barcha tomonlar",
    clearFilters: "Tozalash",
    noResults: "Tanlangan filtrlarga mos o‘zgarish yo‘q.",
    before: "Oldin",
    after: "Keyin",
    legalEffect: "Yuridik ahamiyat",
    affectedParty: "Ta’sirlangan tomon",
    recommendation: "Tavsiya",
    confidence: "AI ishonchi",
    reviewed: "Ko‘rib chiqildi",
    markReviewed: "Ko‘rib chiqilgan deb belgilash",
    syncScroll: "Sinxron aylantirish",
    versionOne: "1-versiya",
    versionTwo: "2-versiya",
    showVersion: "Ko‘rsatish",
    legend: "Belgilashlar",
    unchanged: "O‘zgarishsiz",
    noSources: "Hozircha tasdiqlangan manbalar yo‘q.",
    officialSource: "Rasmiy manba",
    currentAsOf: "Dolzarblik tekshirildi",
    originalLanguage: "Manba tili",
    status: "Holat",
    verified: "Tekshirilgan",
    processing: "Natija hali shakllanmoqda",
    extractionWarning: "Matn cheklangan aniqlik bilan tanildi.",
    riskLabels: { high: "Yuqori", medium: "O‘rta", low: "Past", information: "Ma’lumot" },
    changeLabels: {
      added: "Qo‘shilgan",
      removed: "Olib tashlangan",
      changed: "O‘zgartirilgan",
      moved: "Ko‘chirilgan",
      renumbered: "Qayta raqamlangan",
      formatting: "Format",
      unchanged: "O‘zgarishsiz",
    },
    effectLabels: {
      increased: "Xavf oshdi",
      decreased: "Xavf kamaydi",
      neutral: "Neytral",
      requires_review: "Tekshiruv talab qiladi",
      insufficient_data: "Ma’lumot yetarli emas",
    },
  },
} as const;
