import type { PlatformLocale } from "../lib/platform/routing";
import { platformLocaleValue } from "./platform-localization";

export {
  platformApiError,
  platformLocaleValue,
  type PlatformLocalizedValue,
} from "./platform-localization";

type WidenStrings<T> = T extends string
  ? string
  : T extends readonly (infer U)[]
    ? readonly WidenStrings<U>[]
    : T extends object
      ? { [K in keyof T]: WidenStrings<T[K]> }
      : T;

function definePlatformCopies<T extends Record<PlatformLocale, object>>(
  copies: T,
): Record<PlatformLocale, WidenStrings<T[PlatformLocale]>> {
  // `T[PlatformLocale]` is the union of the structurally equivalent locale
  // branches. Widening their string literals prevents downstream components
  // from treating translated labels as incompatible values.
  return copies as Record<PlatformLocale, WidenStrings<T[PlatformLocale]>>;
}

const dashboard = {
  greeting: { ru: "Добрый день", uz: "Xayrli kun", en: "Good day" },
  question: { ru: "Что нужно решить сегодня?", uz: "Bugun nimani hal qilish kerak?", en: "What would you like to resolve today?" },
  prompt: {
    ru: "Опишите ситуацию или задайте юридический вопрос",
    uz: "Vaziyatni yozing yoki yuridik savol bering",
    en: "Describe your situation or ask a legal question",
  },
  attach: { ru: "Прикрепить документ", uz: "Hujjat biriktirish", en: "Attach a document" },
  removeFile: { ru: "Убрать файл", uz: "Faylni olib tashlash", en: "Remove file" },
  send: { ru: "Начать", uz: "Boshlash", en: "Start" },
  consent: {
    ru: "Согласен(на) на приватную загрузку и автоматизированный анализ выбранного файла.",
    uz: "Tanlangan faylni maxfiy yuklash va avtomatlashtirilgan tahlilga roziman.",
    en: "I consent to the private upload and automated analysis of the selected file.",
  },
  contextPersonal: { ru: "Личное пространство", uz: "Shaxsiy makon", en: "Personal workspace" },
  contextBusiness: { ru: "Бизнес-пространство", uz: "Biznes makoni", en: "Business workspace" },
  quickTitle: { ru: "Быстрый запуск", uz: "Tezkor boshlash", en: "Quick start" },
  continueTitle: { ru: "Продолжить работу", uz: "Ishni davom ettirish", en: "Continue working" },
  attentionTitle: { ru: "Требует внимания", uz: "E’tibor talab qiladi", en: "Needs attention" },
  recentTitle: { ru: "Последние материалы", uz: "So‘nggi materiallar", en: "Recent items" },
  emptyAttention: {
    ru: "Срочных действий нет. Новые сроки, анализы и комментарии появятся здесь.",
    uz: "Shoshilinch harakatlar yo‘q. Yangi muddatlar, tahlillar va izohlar shu yerda ko‘rinadi.",
    en: "Nothing urgent right now. New deadlines, analyses and comments will appear here.",
  },
  emptyRecent: {
    ru: "Создайте дело или документ — JURO сохранит контекст и следующий шаг.",
    uz: "Ish yoki hujjat yarating — JURO kontekst va keyingi qadamni saqlaydi.",
    en: "Create a matter or document, and JURO will preserve the context and next step.",
  },
  openAll: { ru: "Открыть все", uz: "Barchasini ochish", en: "View all" },
  refresh: { ru: "Обновить рабочее пространство", uz: "Ish makonini yangilash", en: "Refresh workspace" },
  fileTooLarge: { ru: "Файл превышает 10 МБ.", uz: "Fayl 10 MB dan katta.", en: "The file exceeds 10 MB." },
  loadError: { ru: "Не удалось загрузить рабочее пространство.", uz: "Ish makonini yuklab bo‘lmadi.", en: "We could not load your workspace." },
  uploadError: { ru: "Файл не удалось загрузить.", uz: "Faylni yuklab bo‘lmadi.", en: "We could not upload the file." },
  intakeError: { ru: "Не удалось защищённо передать вопрос.", uz: "Savolni himoyalangan tarzda uzatib bo‘lmadi.", en: "We could not submit your question securely." },
  fileTooLarge50: { ru: "Размер файла превышает 50 МБ.", uz: "Fayl hajmi 50 MB dan oshadi.", en: "The file exceeds 50 MB." },
  myMatters: { ru: "Мои дела", uz: "Mening ishlarim", en: "My matters" },
  myMattersDescription: { ru: "Сроки, документы и планы действий в одном месте.", uz: "Muddatlar, hujjatlar va harakatlar rejalari bir joyda.", en: "Deadlines, documents and action plans in one place." },
  hashing: { ru: "Проверяем целостность файла…", uz: "Fayl yaxlitligi tekshirilmoqda…", en: "Checking file integrity…" },
  finalizing: { ru: "Защищённо сохраняем файл для анализа…", uz: "Fayl tahlil uchun himoyalangan tarzda saqlanmoqda…", en: "Securely saving the file for analysis…" },
  uploading: { ru: "Передаём файл…", uz: "Fayl yuborilmoqda…", en: "Uploading file…" },
  uploadingPercent: { ru: "Передаём файл", uz: "Fayl yuborilmoqda", en: "Uploading file" },
  comparisonFailed: { ru: "Сравнение остановлено — можно повторить этап", uz: "Taqqoslash to‘xtadi — bosqichni takrorlash mumkin", en: "Comparison stopped — you can retry the stage" },
  comparisonProcessing: { ru: "Сравнение обрабатывается", uz: "Taqqoslash qayta ishlanmoqda", en: "Comparison in progress" },
  analysisAwaiting: { ru: "Файл сохранён; AI-анализ ожидает подключения", uz: "Fayl saqlandi; AI-tahlil ulanishni kutmoqda", en: "File saved; AI analysis is waiting for a provider" },
  analysisIncomplete: { ru: "Анализ документа не завершён", uz: "Hujjat tahlili yakunlanmagan", en: "Document analysis is incomplete" },
  voiceMode: { ru: "Открыть голосовой режим", uz: "Ovozli rejimni ochish", en: "Open voice mode" },
  uploadProgress: { ru: "Прогресс загрузки файла", uz: "Fayl yuklash jarayoni", en: "File upload progress" },
  workday: { ru: "Рабочий день", uz: "Ish kuni", en: "Workday" },
  today: { ru: "Сегодня", uz: "Bugun", en: "Today" },
  synchronizing: { ru: "Синхронизируем", uz: "Sinxronlanmoqda", en: "Synchronizing" },
  nothingUrgentToday: { ru: "На сегодня срочных событий нет", uz: "Bugun shoshilinch voqealar yo‘q", en: "Nothing urgent today" },
  openCalendar: { ru: "Открыть календарь", uz: "Kalendarni ochish", en: "Open calendar" },
  retry: { ru: "Повторить", uz: "Qayta urinish", en: "Try again" },
  loadingContext: { ru: "Загружаем рабочий контекст", uz: "Ish konteksti yuklanmoqda", en: "Loading workspace context" },
  attentionDescription: { ru: "Сроки, незавершённая обработка и новые события", uz: "Muddatlar, tugallanmagan qayta ishlash va yangi voqealar", en: "Deadlines, unfinished processing and new events" },
  recentDescription: { ru: "Дела и документы, изменённые последними", uz: "Oxirgi o‘zgartirilgan ish va hujjatlar", en: "Recently updated matters and documents" },
  workspaceSummary: { ru: "Сводка пространства", uz: "Makon xulosasi", en: "Workspace summary" },
  activeMatters: { ru: "активных дел", uz: "faol ish", en: "active matters" },
  documentsCount: { ru: "документов", uz: "hujjat", en: "documents" },
  consultationsCount: { ru: "консультаций", uz: "maslahat", en: "consultations" },
  newEvents: { ru: "новых событий", uz: "yangi voqea", en: "new events" },
  journeyLabel: { ru: "Золотой юридический маршрут JURO", uz: "JURO oltin yuridik yo‘li", en: "JURO legal workflow" },
  journeySteps: {
    ru: ["Вопрос", "Источники", "Анализ", "Действие"],
    uz: ["Savol", "Manbalar", "Tahlil", "Harakat"],
    en: ["Question", "Sources", "Analysis", "Action"],
  },
  actions: {
    ask: {
      title: { ru: "Задать вопрос AI-юристу", uz: "AI-yuristga savol berish", en: "Ask the AI legal assistant" },
      description: { ru: "Отделим факты от предположений и предложим следующий шаг.", uz: "Faktlarni taxminlardan ajratib, keyingi qadamni taklif qilamiz.", en: "Separate facts from assumptions and identify the next step." },
    },
    review: {
      title: { ru: "Проверить документ на риски", uz: "Hujjat xavflarini tekshirish", en: "Review a document for risks" },
      description: { ru: "Покажем спорные условия, пробелы и вопросы для проверки.", uz: "Bahsli shartlar, bo‘shliqlar va tekshiruv savollarini ko‘rsatamiz.", en: "Identify disputed terms, gaps and questions that need review." },
    },
    compare: {
      title: { ru: "Сравнить две версии", uz: "Ikki versiyani taqqoslash", en: "Compare two versions" },
      description: { ru: "Найдём добавления, удаления и изменение вашего риска.", uz: "Qo‘shish, olib tashlash va xavf o‘zgarishini topamiz.", en: "Find additions, removals and changes to your risk." },
    },
    create: {
      title: { ru: "Создать документ", uz: "Hujjat yaratish", en: "Create a document" },
      description: { ru: "Соберём проект по шагам и сохраним редактируемую версию.", uz: "Loyihani bosqichma-bosqich tuzib, tahrirlanadigan versiyani saqlaymiz.", en: "Build a draft step by step and keep an editable version." },
    },
    plan: {
      title: { ru: "Составить план действий", uz: "Harakatlar rejasini tuzish", en: "Create an action plan" },
      description: { ru: "Свяжем задачу, сроки, документы и ответственных.", uz: "Vazifa, muddat, hujjat va mas’ullarni bog‘laymiz.", en: "Connect the task, deadlines, documents and responsible people." },
    },
    lawyer: {
      title: { ru: "Передать живому юристу", uz: "Jonli yuristga topshirish", en: "Share with a lawyer" },
      description: { ru: "Передадим только выбранный вами контекст и документы.", uz: "Faqat siz tanlagan kontekst va hujjatlarni yuboramiz.", en: "Share only the context and documents you select." },
    },
  },
} as const;

export function dashboardCopy(locale: PlatformLocale) {
  return {
    greeting: platformLocaleValue(locale, dashboard.greeting),
    question: platformLocaleValue(locale, dashboard.question),
    prompt: platformLocaleValue(locale, dashboard.prompt),
    attach: platformLocaleValue(locale, dashboard.attach),
    removeFile: platformLocaleValue(locale, dashboard.removeFile),
    send: platformLocaleValue(locale, dashboard.send),
    consent: platformLocaleValue(locale, dashboard.consent),
    contextPersonal: platformLocaleValue(locale, dashboard.contextPersonal),
    contextBusiness: platformLocaleValue(locale, dashboard.contextBusiness),
    quickTitle: platformLocaleValue(locale, dashboard.quickTitle),
    continueTitle: platformLocaleValue(locale, dashboard.continueTitle),
    attentionTitle: platformLocaleValue(locale, dashboard.attentionTitle),
    recentTitle: platformLocaleValue(locale, dashboard.recentTitle),
    emptyAttention: platformLocaleValue(locale, dashboard.emptyAttention),
    emptyRecent: platformLocaleValue(locale, dashboard.emptyRecent),
    openAll: platformLocaleValue(locale, dashboard.openAll),
    refresh: platformLocaleValue(locale, dashboard.refresh),
    fileTooLarge: platformLocaleValue(locale, dashboard.fileTooLarge),
    loadError: platformLocaleValue(locale, dashboard.loadError),
    uploadError: platformLocaleValue(locale, dashboard.uploadError),
    intakeError: platformLocaleValue(locale, dashboard.intakeError),
    fileTooLarge50: platformLocaleValue(locale, dashboard.fileTooLarge50),
    myMatters: platformLocaleValue(locale, dashboard.myMatters),
    myMattersDescription: platformLocaleValue(locale, dashboard.myMattersDescription),
    hashing: platformLocaleValue(locale, dashboard.hashing),
    finalizing: platformLocaleValue(locale, dashboard.finalizing),
    uploading: platformLocaleValue(locale, dashboard.uploading),
    uploadingPercent: platformLocaleValue(locale, dashboard.uploadingPercent),
    comparisonFailed: platformLocaleValue(locale, dashboard.comparisonFailed),
    comparisonProcessing: platformLocaleValue(locale, dashboard.comparisonProcessing),
    analysisAwaiting: platformLocaleValue(locale, dashboard.analysisAwaiting),
    analysisIncomplete: platformLocaleValue(locale, dashboard.analysisIncomplete),
    voiceMode: platformLocaleValue(locale, dashboard.voiceMode),
    uploadProgress: platformLocaleValue(locale, dashboard.uploadProgress),
    workday: platformLocaleValue(locale, dashboard.workday),
    today: platformLocaleValue(locale, dashboard.today),
    synchronizing: platformLocaleValue(locale, dashboard.synchronizing),
    nothingUrgentToday: platformLocaleValue(locale, dashboard.nothingUrgentToday),
    openCalendar: platformLocaleValue(locale, dashboard.openCalendar),
    retry: platformLocaleValue(locale, dashboard.retry),
    loadingContext: platformLocaleValue(locale, dashboard.loadingContext),
    attentionDescription: platformLocaleValue(locale, dashboard.attentionDescription),
    recentDescription: platformLocaleValue(locale, dashboard.recentDescription),
    workspaceSummary: platformLocaleValue(locale, dashboard.workspaceSummary),
    activeMatters: platformLocaleValue(locale, dashboard.activeMatters),
    documentsCount: platformLocaleValue(locale, dashboard.documentsCount),
    consultationsCount: platformLocaleValue(locale, dashboard.consultationsCount),
    newEvents: platformLocaleValue(locale, dashboard.newEvents),
    journeyLabel: platformLocaleValue(locale, dashboard.journeyLabel),
    journeySteps: dashboard.journeySteps[locale],
    actions: Object.fromEntries(Object.entries(dashboard.actions).map(([key, value]) => [
      key,
      {
        title: platformLocaleValue(locale, value.title),
        description: platformLocaleValue(locale, value.description),
      },
    ])) as Record<keyof typeof dashboard.actions, { title: string; description: string }>,
  };
}

export const comparisonText = definePlatformCopies({
  ru: {
    tool: "Анализ документов",
    title: "Проверяйте риски и сравнивайте редакции",
    description: "JURO хранит исходные версии неизменяемыми и отделяет точный redline от юридической AI-оценки.",
    singleMode: "Проверить один документ",
    compareMode: "Сравнить две версии",
    versionOne: "Версия 1 · исходный документ",
    versionTwo: "Версия 2 · новая редакция",
    chooseFile: "Перетащите файл или выберите на устройстве",
    chooseStored: "Или выберите сохранённый файл",
    replace: "Заменить",
    remove: "Удалить",
    swap: "Поменять версии местами",
    consent: "Согласен(на) на приватное сохранение и автоматизированное сравнение выбранных версий.",
    start: "Начать сравнение",
    supported: "PDF или DOCX до 10 МБ. Для сканов требуется подключённый OCR.",
    recent: "Сохранённые сравнения",
    noComparisons: "Сравнений пока нет.",
    identicalWarning: "Файлы идентичны по SHA-256; JURO всё равно подтвердит отсутствие изменений.",
    differentWarning: "Документы существенно различаются и могут не быть версиями друг друга.",
    processing: "Сравнение выполняется",
    stages: {
      uploaded: "Загрузка",
      extracting_version_one: "Извлечение текста версии 1",
      extracting_version_two: "Извлечение текста версии 2",
      structuring: "Распознавание структуры",
      diffing: "Точный поиск изменений",
      legal_analysis: "Анализ изменения рисков",
      completed: "Готово",
      failed: "Ошибка",
    },
    retry: "Повторить неудавшийся этап",
    open: "Открыть результат",
    loadError: "Сравнения не загрузились.",
    createError: "Сравнение не создано.",
    processError: "Сравнение не завершено.",
    retryError: "Повторная обработка не завершена.",
    savedDescription: "Результаты сохраняются и повторно открываются в вашем пространстве.",
    refreshAria: "Обновить сравнения",
    comparedWith: "с",
    fromStorage: "из хранилища JURO",
    fromDevice: "с устройства",
  },
  uz: {
    tool: "Hujjatlarni tahlil qilish",
    title: "Xavflarni tekshiring va tahrirlarni taqqoslang",
    description: "JURO asl versiyalarni o‘zgarmas holda saqlaydi va aniq redline’ni yuridik AI-bahodan ajratadi.",
    singleMode: "Bitta hujjatni tekshirish",
    compareMode: "Ikki versiyani taqqoslash",
    versionOne: "1-versiya · dastlabki hujjat",
    versionTwo: "2-versiya · yangi tahrir",
    chooseFile: "Faylni tashlang yoki qurilmadan tanlang",
    chooseStored: "Yoki saqlangan faylni tanlang",
    replace: "Almashtirish",
    remove: "Olib tashlash",
    swap: "Versiyalarni joyini almashtirish",
    consent: "Tanlangan versiyalarni maxfiy saqlash va avtomatlashtirilgan taqqoslashga roziman.",
    start: "Taqqoslashni boshlash",
    supported: "10 MB gacha PDF yoki DOCX. Skanlar uchun ulangan OCR talab qilinadi.",
    recent: "Saqlangan taqqoslashlar",
    noComparisons: "Hozircha taqqoslashlar yo‘q.",
    identicalWarning: "Fayllar SHA-256 bo‘yicha bir xil; JURO o‘zgarish yo‘qligini baribir tasdiqlaydi.",
    differentWarning: "Hujjatlar keskin farq qiladi va bir hujjatning versiyalari bo‘lmasligi mumkin.",
    processing: "Taqqoslash bajarilmoqda",
    stages: {
      uploaded: "Yuklash",
      extracting_version_one: "1-versiya matnini ajratish",
      extracting_version_two: "2-versiya matnini ajratish",
      structuring: "Tuzilmani aniqlash",
      diffing: "Aniq o‘zgarishlarni qidirish",
      legal_analysis: "Xavf o‘zgarishini tahlil qilish",
      completed: "Tayyor",
      failed: "Xato",
    },
    retry: "Muvaffaqiyatsiz bosqichni takrorlash",
    open: "Natijani ochish",
    loadError: "Taqqoslashlar yuklanmadi.",
    createError: "Taqqoslash yaratilmadi.",
    processError: "Taqqoslash yakunlanmadi.",
    retryError: "Qayta ishlash yakunlanmadi.",
    savedDescription: "Natijalar makoningizda saqlanadi va qayta ochiladi.",
    refreshAria: "Taqqoslashlarni yangilash",
    comparedWith: "va",
    fromStorage: "JURO omboridan",
    fromDevice: "qurilmadan",
  },
  en: {
    tool: "Document analysis",
    title: "Review risks and compare revisions",
    description: "JURO preserves the original versions and keeps the exact redline separate from the AI legal assessment.",
    singleMode: "Review one document",
    compareMode: "Compare two versions",
    versionOne: "Version 1 · original document",
    versionTwo: "Version 2 · revised document",
    chooseFile: "Drop a file here or choose one from your device",
    chooseStored: "Or select a saved file",
    replace: "Replace",
    remove: "Remove",
    swap: "Swap versions",
    consent: "I consent to the private storage and automated comparison of the selected versions.",
    start: "Start comparison",
    supported: "PDF or DOCX up to 10 MB. Scanned documents require a connected OCR service.",
    recent: "Saved comparisons",
    noComparisons: "No comparisons yet.",
    identicalWarning: "The files have identical SHA-256 hashes; JURO will still confirm that there are no changes.",
    differentWarning: "The documents differ substantially and may not be versions of the same document.",
    processing: "Comparison in progress",
    stages: {
      uploaded: "Upload",
      extracting_version_one: "Extracting version 1 text",
      extracting_version_two: "Extracting version 2 text",
      structuring: "Detecting structure",
      diffing: "Finding exact changes",
      legal_analysis: "Assessing changes in risk",
      completed: "Complete",
      failed: "Failed",
    },
    retry: "Retry failed stage",
    open: "Open result",
    loadError: "Comparisons could not be loaded.",
    createError: "The comparison could not be created.",
    processError: "The comparison could not be completed.",
    retryError: "The comparison could not be processed again.",
    savedDescription: "Results are saved in your workspace and can be reopened at any time.",
    refreshAria: "Refresh comparisons",
    comparedWith: "with",
    fromStorage: "from JURO storage",
    fromDevice: "from this device",
  },
});

export const comparisonResultText = definePlatformCopies({
  ru: {
    back: "Анализ документов",
    generated: "Анализ сформирован",
    uploaded: "Загружено",
    pages: "страниц",
    size: "Размер",
    documentLanguage: "Язык",
    recognition: "Распознавание",
    openVersion: "Открыть версию",
    qualityGood: "Текст извлечён",
    qualityLimited: "Ограниченная точность",
    qualityOcr: "Требуется OCR",
    partial: "Точный redline готов; юридическая AI-оценка доступна частично",
    retry: "Повторить обработку",
    delete: "Удалить сравнение",
    deleteConfirm: "Удалить сравнение? Оно исчезнет из рабочего пространства согласно политике хранения.",
    exportPdf: "Скачать PDF-отчёт",
    exportDocx: "Скачать DOCX redline",
    exportCreatePdf: "Создать PDF-отчёт",
    exportCreateDocx: "Создать DOCX redline",
    exportPreparing: "Экспорт формируется",
    exportRetry: "Повторить экспорт",
    exportDelete: "Удалить экспорт",
    exportFailed: "Экспорт не сформирован. Повторите действие.",
    consult: "Передать юристу",
    edit: "Открыть конструктор",
    saveToCase: "Сохранить в дело",
    chooseCase: "Выберите дело",
    caseSaved: "Сравнение связано с делом",
    noCases: "Дел пока нет",
    createCase: "Создать дело",
    tabs: {
      summary: "Кратко",
      all: "Все изменения",
      side: "Две версии рядом",
      redline: "Redline",
      risks: "Изменение рисков",
      sources: "Источники",
      recommendations: "Рекомендации",
    },
    metrics: {
      changes: "изменений",
      material: "существенных",
      increased: "повышают риск",
      decreased: "снижают риск",
      similarity: "сходство версий",
    },
    overallRisk: "Общий уровень риска",
    changedSections: "Изменённые разделы",
    noChangedSections: "Названия разделов не распознаны.",
    likelyDifferent: "Документы существенно различаются и могут не быть версиями друг друга. Результат сохранён, но требует особенно внимательной проверки.",
    aiUnavailable: "AI-провайдер не подключён или временно недоступен. Точный diff выполнен, но юридический эффект отмечен как требующий проверки.",
    sourceUnavailable: "Источник временно не проверен",
    sourceUnavailableDetail: "Для этого вывода нет подтверждённого акта в серверном реестре JURO.",
    filters: "Фильтры",
    onlyMaterial: "Только существенные",
    increased: "Риск повысился",
    decreased: "Риск снизился",
    added: "Добавлено",
    removed: "Удалено",
    changed: "Изменено",
    moved: "Перемещено",
    renumbered: "Перенумеровано",
    formatting: "Только форматирование",
    hasSource: "Есть источник",
    lowConfidence: "Уверенность ниже 70%",
    sectionFilter: "Раздел документа",
    allSections: "Все разделы",
    partyFilter: "Затронутая сторона",
    allParties: "Все стороны",
    clearFilters: "Сбросить",
    noResults: "По выбранным фильтрам изменений нет.",
    before: "Было",
    after: "Стало",
    legalEffect: "Юридическое значение",
    affectedParty: "Затронутая сторона",
    recommendation: "Рекомендация",
    confidence: "Уверенность AI",
    reviewed: "Просмотрено",
    markReviewed: "Отметить просмотренным",
    decisionLabel: "Решение по изменению",
    acceptChange: "Принять",
    rejectChange: "Отклонить",
    clearDecision: "Сбросить решение",
    decisionAccepted: "Изменение принято",
    decisionRejected: "Изменение отклонено",
    decisionPending: "Решение не принято",
    decisionSaving: "Сохраняется…",
    decisionSaveError: "Решение не сохранено.",
    syncScroll: "Синхронная прокрутка",
    versionOne: "Версия 1",
    versionTwo: "Версия 2",
    showVersion: "Показать",
    legend: "Легенда",
    unchanged: "Без изменений",
    noSources: "Подтверждённых источников пока нет.",
    officialSource: "Официальный источник",
    currentAsOf: "Актуальность проверена",
    originalLanguage: "Язык источника",
    status: "Статус",
    verified: "Проверен",
    processing: "Результат ещё формируется",
    loadError: "Сравнение не найдено.",
    processingError: "Сравнение не завершено.",
    reviewSaveError: "Статус не сохранён.",
    deleteError: "Сравнение не удалено.",
    caseLinkError: "Связь с делом не сохранена.",
    exportCreateError: "Экспорт не создан.",
    exportDeleteError: "Экспорт не удалён.",
    unavailableTitle: "Сравнение недоступно",
    versionMetadataAria: "Сведения о версиях",
    resultViewAria: "Представление результата",
    extractionWarning: "Текст распознан с ограниченной точностью.",
    riskLabels: { high: "Высокий", medium: "Средний", low: "Низкий", information: "Информация" },
    changeLabels: {
      added: "Добавлено",
      removed: "Удалено",
      changed: "Изменено",
      moved: "Перемещено",
      renumbered: "Перенумеровано",
      formatting: "Форматирование",
      unchanged: "Без изменений",
    },
    effectLabels: {
      increased: "Риск повысился",
      decreased: "Риск снизился",
      neutral: "Нейтрально",
      requires_review: "Требует проверки",
      insufficient_data: "Недостаточно данных",
    },
  },
  uz: {
    back: "Hujjatlarni tahlil qilish",
    generated: "Tahlil yaratildi",
    uploaded: "Yuklangan",
    pages: "sahifa",
    size: "Hajmi",
    documentLanguage: "Til",
    recognition: "Tanib olish",
    openVersion: "Versiyani ochish",
    qualityGood: "Matn ajratildi",
    qualityLimited: "Aniqlik cheklangan",
    qualityOcr: "OCR talab qilinadi",
    partial: "Aniq redline tayyor; yuridik AI-baho qisman mavjud",
    retry: "Qayta ishlash",
    delete: "Taqqoslashni o‘chirish",
    deleteConfirm: "Taqqoslash o‘chirilsinmi? U saqlash siyosatiga muvofiq ish makonidan yo‘qoladi.",
    exportPdf: "PDF-hisobotni yuklash",
    exportDocx: "DOCX redline’ni yuklash",
    exportCreatePdf: "PDF-hisobot yaratish",
    exportCreateDocx: "DOCX redline yaratish",
    exportPreparing: "Eksport yaratilmoqda",
    exportRetry: "Eksportni takrorlash",
    exportDelete: "Eksportni o‘chirish",
    exportFailed: "Eksport yaratilmadi. Qayta urinib ko‘ring.",
    consult: "Yuristga topshirish",
    edit: "Konstruktorni ochish",
    saveToCase: "Ishga saqlash",
    chooseCase: "Ishni tanlang",
    caseSaved: "Taqqoslash ishga bog‘landi",
    noCases: "Hozircha ishlar yo‘q",
    createCase: "Ish yaratish",
    tabs: {
      summary: "Qisqacha",
      all: "Barcha o‘zgarishlar",
      side: "Ikki versiya yonma-yon",
      redline: "Redline",
      risks: "Xavf o‘zgarishi",
      sources: "Manbalar",
      recommendations: "Tavsiyalar",
    },
    metrics: {
      changes: "o‘zgarish",
      material: "muhim",
      increased: "xavfni oshiradi",
      decreased: "xavfni kamaytiradi",
      similarity: "versiyalar o‘xshashligi",
    },
    overallRisk: "Umumiy xavf darajasi",
    changedSections: "O‘zgargan bo‘limlar",
    noChangedSections: "Bo‘lim nomlari aniqlanmadi.",
    likelyDifferent: "Hujjatlar keskin farq qiladi va bir hujjatning versiyalari bo‘lmasligi mumkin. Natija saqlandi, ammo alohida e’tibor bilan tekshirish kerak.",
    aiUnavailable: "AI-provayder ulanmagan yoki vaqtincha ishlamaydi. Aniq diff bajarildi, ammo yuridik ta’sir tekshiruv talab qiladi.",
    sourceUnavailable: "Manba vaqtincha tekshirilmagan",
    sourceUnavailableDetail: "Bu xulosa uchun JURO server reyestrida tasdiqlangan hujjat yo‘q.",
    filters: "Filtrlar",
    onlyMaterial: "Faqat muhimlari",
    increased: "Xavf oshdi",
    decreased: "Xavf kamaydi",
    added: "Qo‘shilgan",
    removed: "Olib tashlangan",
    changed: "O‘zgartirilgan",
    moved: "Ko‘chirilgan",
    renumbered: "Qayta raqamlangan",
    formatting: "Faqat format",
    hasSource: "Manbasi bor",
    lowConfidence: "Ishonch 70% dan past",
    sectionFilter: "Hujjat bo‘limi",
    allSections: "Barcha bo‘limlar",
    partyFilter: "Ta’sirlangan tomon",
    allParties: "Barcha tomonlar",
    clearFilters: "Tozalash",
    noResults: "Tanlangan filtrlarga mos o‘zgarish yo‘q.",
    before: "Oldin",
    after: "Keyin",
    legalEffect: "Yuridik ahamiyat",
    affectedParty: "Ta’sirlangan tomon",
    recommendation: "Tavsiya",
    confidence: "AI ishonchi",
    reviewed: "Ko‘rib chiqildi",
    markReviewed: "Ko‘rib chiqilgan deb belgilash",
    decisionLabel: "O‘zgarish bo‘yicha qaror",
    acceptChange: "Qabul qilish",
    rejectChange: "Rad etish",
    clearDecision: "Qarorni bekor qilish",
    decisionAccepted: "O‘zgarish qabul qilindi",
    decisionRejected: "O‘zgarish rad etildi",
    decisionPending: "Qaror qabul qilinmagan",
    decisionSaving: "Saqlanmoqda…",
    decisionSaveError: "Qaror saqlanmadi.",
    syncScroll: "Sinxron aylantirish",
    versionOne: "1-versiya",
    versionTwo: "2-versiya",
    showVersion: "Ko‘rsatish",
    legend: "Belgilashlar",
    unchanged: "O‘zgarishsiz",
    noSources: "Hozircha tasdiqlangan manbalar yo‘q.",
    officialSource: "Rasmiy manba",
    currentAsOf: "Dolzarblik tekshirildi",
    originalLanguage: "Manba tili",
    status: "Holat",
    verified: "Tekshirilgan",
    processing: "Natija hali shakllanmoqda",
    loadError: "Taqqoslash topilmadi.",
    processingError: "Taqqoslash yakunlanmadi.",
    reviewSaveError: "Holat saqlanmadi.",
    deleteError: "Taqqoslash o‘chirilmadi.",
    caseLinkError: "Ish bilan bog‘lanish saqlanmadi.",
    exportCreateError: "Eksport yaratilmadi.",
    exportDeleteError: "Eksport o‘chirilmadi.",
    unavailableTitle: "Taqqoslash mavjud emas",
    versionMetadataAria: "Versiyalar haqida ma’lumot",
    resultViewAria: "Natija ko‘rinishi",
    extractionWarning: "Matn cheklangan aniqlik bilan tanildi.",
    riskLabels: { high: "Yuqori", medium: "O‘rta", low: "Past", information: "Ma’lumot" },
    changeLabels: {
      added: "Qo‘shilgan",
      removed: "Olib tashlangan",
      changed: "O‘zgartirilgan",
      moved: "Ko‘chirilgan",
      renumbered: "Qayta raqamlangan",
      formatting: "Format",
      unchanged: "O‘zgarishsiz",
    },
    effectLabels: {
      increased: "Xavf oshdi",
      decreased: "Xavf kamaydi",
      neutral: "Neytral",
      requires_review: "Tekshiruv talab qiladi",
      insufficient_data: "Ma’lumot yetarli emas",
    },
  },
  en: {
    back: "Document analysis",
    generated: "Analysis generated",
    uploaded: "Uploaded",
    pages: "pages",
    size: "Size",
    documentLanguage: "Language",
    recognition: "Recognition",
    openVersion: "Open version",
    qualityGood: "Text extracted",
    qualityLimited: "Limited accuracy",
    qualityOcr: "OCR required",
    partial: "The exact redline is ready; the AI legal assessment is only partially available",
    retry: "Retry processing",
    delete: "Delete comparison",
    deleteConfirm: "Delete this comparison? It will be removed from the workspace in accordance with the retention policy.",
    exportPdf: "Download PDF report",
    exportDocx: "Download DOCX redline",
    exportCreatePdf: "Create PDF report",
    exportCreateDocx: "Create DOCX redline",
    exportPreparing: "Preparing export",
    exportRetry: "Retry export",
    exportDelete: "Delete export",
    exportFailed: "The export could not be generated. Please try again.",
    consult: "Share with a lawyer",
    edit: "Open document builder",
    saveToCase: "Save to matter",
    chooseCase: "Select a matter",
    caseSaved: "Comparison linked to matter",
    noCases: "No matters yet",
    createCase: "Create a matter",
    tabs: {
      summary: "Summary",
      all: "All changes",
      side: "Side by side",
      redline: "Redline",
      risks: "Risk changes",
      sources: "Sources",
      recommendations: "Recommendations",
    },
    metrics: {
      changes: "changes",
      material: "material",
      increased: "increase risk",
      decreased: "reduce risk",
      similarity: "version similarity",
    },
    overallRisk: "Overall risk level",
    changedSections: "Changed sections",
    noChangedSections: "Section names were not detected.",
    likelyDifferent: "The documents differ substantially and may not be versions of the same document. The result has been saved, but requires especially careful review.",
    aiUnavailable: "The AI provider is not connected or is temporarily unavailable. The exact diff is complete, but the legal effect requires review.",
    sourceUnavailable: "Source temporarily unverified",
    sourceUnavailableDetail: "JURO's server registry contains no verified legal act supporting this conclusion.",
    filters: "Filters",
    onlyMaterial: "Material changes only",
    increased: "Risk increased",
    decreased: "Risk decreased",
    added: "Added",
    removed: "Removed",
    changed: "Changed",
    moved: "Moved",
    renumbered: "Renumbered",
    formatting: "Formatting only",
    hasSource: "Has a source",
    lowConfidence: "Confidence below 70%",
    sectionFilter: "Document section",
    allSections: "All sections",
    partyFilter: "Affected party",
    allParties: "All parties",
    clearFilters: "Clear",
    noResults: "No changes match the selected filters.",
    before: "Before",
    after: "After",
    legalEffect: "Legal effect",
    affectedParty: "Affected party",
    recommendation: "Recommendation",
    confidence: "AI confidence",
    reviewed: "Reviewed",
    markReviewed: "Mark as reviewed",
    decisionLabel: "Decision on change",
    acceptChange: "Accept",
    rejectChange: "Reject",
    clearDecision: "Clear decision",
    decisionAccepted: "Change accepted",
    decisionRejected: "Change rejected",
    decisionPending: "No decision",
    decisionSaving: "Saving…",
    decisionSaveError: "The decision could not be saved.",
    syncScroll: "Synchronized scrolling",
    versionOne: "Version 1",
    versionTwo: "Version 2",
    showVersion: "Show",
    legend: "Legend",
    unchanged: "Unchanged",
    noSources: "No verified sources yet.",
    officialSource: "Official source",
    currentAsOf: "Current as of",
    originalLanguage: "Source language",
    status: "Status",
    verified: "Verified",
    processing: "The result is still being generated",
    loadError: "The comparison could not be found.",
    processingError: "The comparison could not be completed.",
    reviewSaveError: "The review status could not be saved.",
    deleteError: "The comparison could not be deleted.",
    caseLinkError: "The comparison could not be linked to the matter.",
    exportCreateError: "The export could not be created.",
    exportDeleteError: "The export could not be deleted.",
    unavailableTitle: "Comparison unavailable",
    versionMetadataAria: "Version details",
    resultViewAria: "Result view",
    extractionWarning: "The text was recognized with limited accuracy.",
    riskLabels: { high: "High", medium: "Medium", low: "Low", information: "Information" },
    changeLabels: {
      added: "Added",
      removed: "Removed",
      changed: "Changed",
      moved: "Moved",
      renumbered: "Renumbered",
      formatting: "Formatting",
      unchanged: "Unchanged",
    },
    effectLabels: {
      increased: "Risk increased",
      decreased: "Risk decreased",
      neutral: "Neutral",
      requires_review: "Requires review",
      insufficient_data: "Insufficient data",
    },
  },
});
