import Link from "next/link";
import { Bot, BriefcaseBusiness, CalendarCheck2, FileCheck2, FilePenLine, History, MessageSquareText, Plus, ShieldCheck, UserRound } from "lucide-react";
import type { AccountType, PlatformLocale, PlatformModule } from "../../lib/platform/routing";
import { ActionPlanClient } from "./ActionPlanClient";
import { ConsultationsClient } from "./ConsultationsClient";

const titles: Record<PlatformModule, { ru: string; uz: string }> = {
  main:{ru:"Главная",uz:"Bosh sahifa"},"ai-chat":{ru:"AI-юрист",uz:"AI-yurist"},cases:{ru:"Мои дела",uz:"Mening ishlarim"},"document-review":{ru:"Проверить документ",uz:"Hujjatni tekshirish"},"action-plan":{ru:"План действий",uz:"Harakatlar rejasi"},consultations:{ru:"Консультации",uz:"Maslahatlar"},history:{ru:"История",uz:"Tarix"},billing:{ru:"Тариф и оплата",uz:"Tarif va to‘lov"},security:{ru:"Безопасность",uz:"Xavfsizlik"},help:{ru:"Помощь",uz:"Yordam"},profile:{ru:"Профиль",uz:"Profil"},settings:{ru:"Настройки языка",uz:"Til sozlamalari"},
};

export function ModuleContent({ locale, accountType, module, userName }: { locale: PlatformLocale; accountType: AccountType; module: PlatformModule; userName: string }) {
  const ru=locale==="ru"; const base=`/${locale}/${accountType}`;
  if(module==="action-plan") return <ActionPlanClient locale={locale} accountType={accountType}/>;
  if(module==="consultations") return <ConsultationsClient locale={locale}/>;
  if(module==="main") return <div className="platform-dashboard"><section className="platform-welcome"><span>{new Intl.DateTimeFormat(ru?"ru-RU":"uz-UZ",{dateStyle:"full",timeZone:"Asia/Tashkent"}).format(new Date())}</span><h1>{ru?`Добрый день, ${userName}`:`Xayrli kun, ${userName}`}</h1><p>{ru?"Выберите задачу — JURO сохранит контекст и свяжет результат с вашим рабочим пространством.":"Vazifani tanlang — JURO kontekstni saqlaydi va natijani ish makoningiz bilan bog‘laydi."}</p></section><section className="platform-quick-grid">{[["ai-chat",Bot,ru?"Задать вопрос AI-юристу":"AI-yuristga savol berish"],["document-review",FileCheck2,ru?"Проверить документ":"Hujjatni tekshirish"],["document-builder",FilePenLine,ru?"Создать документ":"Hujjat yaratish"],["action-plan",CalendarCheck2,ru?"Получить план действий":"Harakatlar rejasini olish"],["cases",BriefcaseBusiness,ru?"Открыть мои дела":"Ishlarimni ochish"],["consultations",MessageSquareText,ru?"Выбрать консультацию":"Maslahatni tanlash"]].map(([slug,Icon,label])=><Link href={`${base}/${slug}`} key={slug as string}><Icon/><strong>{label as string}</strong><span>→</span></Link>)}</section><section className="platform-dashboard-grid"><article><h2>{ru?"Последние обращения":"So‘nggi murojaatlar"}</h2><div className="platform-empty"><History/><p>{ru?"Здесь появятся реальные обращения после первого сохранённого действия.":"Birinchi saqlangan harakatdan so‘ng haqiqiy murojaatlar shu yerda paydo bo‘ladi."}</p></div></article><article><h2>{ru?"Следующее полезное действие":"Keyingi foydali harakat"}</h2><p>{accountType==="business"?(ru?"Создайте бизнес-документ или откройте дело для команды.":"Biznes hujjatini yarating yoki jamoa uchun ish oching."):(ru?"Опишите юридическую ситуацию или выберите готовый документ.":"Yuridik vaziyatni yozing yoki tayyor hujjatni tanlang.")}</p><Link href={`${base}/document-builder`}><Plus/>{ru?"Создать документ":"Hujjat yaratish"}</Link></article></section></div>;
  const descriptions:Record<PlatformModule,string>={main:"","ai-chat":ru?"Опишите ситуацию. AI-помощник отделит факты от предположений и предложит проверяемые следующие шаги.":"Vaziyatni yozing. AI-yordamchi faktlarni taxminlardan ajratib, tekshiriladigan keyingi qadamlarni taklif qiladi.",cases:ru?"Дела объединяют документы, планы, сроки, доказательства и консультации.":"Ishlar hujjatlar, rejalar, muddatlar, dalillar va maslahatlarni birlashtiradi.","document-review":ru?"Загрузите документ для проверки структуры и возможных рисков.":"Tuzilma va ehtimoliy xavflarni tekshirish uchun hujjat yuklang.","action-plan":ru?"Создавайте план из подтверждённых фактов и отслеживайте реальные выполненные шаги.":"Tasdiqlangan faktlardan reja yarating va haqiqiy bajarilgan qadamlarni kuzating.",consultations:ru?"Передавайте специалисту только выбранный вами контекст.":"Mutaxassisga faqat siz tanlagan kontekstni topshiring.",history:ru?"История формируется из реальных действий в делах и документах.":"Tarix ishlar va hujjatlardagi haqiqiy harakatlardan tuziladi.",billing:ru?"Актуальные условия тарифа отображаются перед подтверждением оплаты.":"Amaldagi tarif shartlari to‘lovni tasdiqlashdan oldin ko‘rsatiladi.",security:ru?"Управляйте доступом, сессиями и передачей документов.":"Kirish, sessiyalar va hujjat uzatishni boshqaring.",help:ru?"Инструкции по работе с инструментами JURO.":"JURO vositalari bilan ishlash bo‘yicha yo‘riqnomalar.",profile:ru?"Профильные данные используются только в подтверждённых вами сценариях.":"Profil ma’lumotlari faqat siz tasdiqlagan ssenariylarda ishlatiladi.",settings:ru?"Переключение языка сохраняет текущий модуль и тип пространства.":"Tilni almashtirish joriy modul va makon turini saqlaydi."};
  const Icon=module==="ai-chat"?Bot:module==="cases"?BriefcaseBusiness:module==="security"?ShieldCheck:UserRound;
  return <section className="platform-module"><header><span><Icon/></span><div><small>JURO</small><h1>{titles[module][locale]}</h1><p>{descriptions[module]}</p></div></header><div className="platform-empty platform-module-empty"><Icon/><h2>{ru?"Рабочих записей пока нет":"Hozircha ish yozuvlari yo‘q"}</h2><p>{ru?"Раздел подключён к отдельному URL. Реальные записи появятся после создания соответствующего объекта.":"Bo‘lim alohida URLga ulangan. Tegishli obyekt yaratilgandan keyin haqiqiy yozuvlar paydo bo‘ladi."}</p></div></section>;
}
