/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.types.jsonc --include-runtime=false --env-interface=WebsiteEnv` (hash: bca88f157e32ed814881014f1f1e8bc1)
interface __BaseEnv_WebsiteEnv {
	PRODUCT_ANALYTICS: AnalyticsEngineDataset;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_WebsiteEnv {}
}
interface WebsiteEnv extends __BaseEnv_WebsiteEnv {}
